###################################################
# header_scene_props.py
# This file contains declarations for scene props
# DO NOT EDIT THIS FILE!
###################################################

sokf_type_container        = 0x00000005
sokf_type_ai_limiter       = 0x00000008
sokf_type_barrier          = 0x00000009
sokf_type_barrier_leave    = 0x0000000a
sokf_type_mask             = 0x000000FF
sokf_add_fire              = 0x00000100
sokf_add_smoke             = 0x00000200
sokf_add_light             = 0x00000400
sokf_place_at_origin       = 0x00001000
sokf_dynamic               = 0x00002000
sokf_invisible             = 0x00004000
sokf_destructible          = 0x00008000
sokf_moveable              = 0x00010000

spbf_hit_points_mask       = 0x0000FFFF
spbf_hit_points_bits       = 20

def spr_hit_points(x):
  return ((x & spbf_hit_points_mask) << spbf_hit_points_bits)

def get_spr_hit_points(y):
  return (y >> spbf_hit_points_bits) & spbf_hit_points_mask

#Animation Mode

spanim_linear              = 0
spanim_loop_linear         = 4
