###################################################
# header_sounds.py
# This file contains declarations for sounds
# DO NOT EDIT THIS FILE!
###################################################

sf_2d        = 0x00000001
sf_looping   = 0x00000002
sf_start_at_random_pos = 0x00000004

sf_priority_10    = 0x000000a0
sf_priority_9     = 0x00000090
sf_priority_8     = 0x00000080
sf_priority_7     = 0x00000070
sf_priority_6     = 0x00000060
sf_priority_5     = 0x00000050
sf_priority_4     = 0x00000040
sf_priority_3     = 0x00000030
sf_priority_2     = 0x00000020
sf_priority_1     = 0x00000010

sf_vol_10         = 0x00000a00
sf_vol_9          = 0x00000900
sf_vol_8          = 0x00000800
sf_vol_7          = 0x00000700
sf_vol_6          = 0x00000600
sf_vol_5          = 0x00000500
sf_vol_4          = 0x00000400
sf_vol_3          = 0x00000300
sf_vol_2          = 0x00000200
sf_vol_1          = 0x00000100

