from header_sounds import *

sounds = [
 ("click", sf_2d|sf_vol_1,["drum_3.ogg"]),
 ("tutorial_1", sf_2d|sf_vol_7,["tutorial_1.ogg"]),
 ("tutorial_2", sf_2d|sf_vol_7,["tutorial_2.ogg"]),
 ("gong", sf_2d|sf_priority_9|sf_vol_7, ["s_cymbals.ogg"]),
 ("quest_taken", sf_2d|sf_priority_9|sf_vol_7, []),
 ("quest_completed", sf_2d|sf_priority_9|sf_vol_7, ["quest_completed.ogg"]),
 ("quest_succeeded", sf_2d|sf_priority_9|sf_vol_7, ["quest_succeeded.ogg"]),
 ("quest_concluded", sf_2d|sf_priority_9|sf_vol_7, ["quest_concluded.ogg"]),
 ("quest_failed", sf_2d|sf_priority_9|sf_vol_7, ["quest_failed.ogg"]),
 ("quest_cancelled", sf_2d|sf_priority_9|sf_vol_7, ["quest_cancelled.ogg"]),
 ("rain",sf_2d|sf_priority_10|sf_vol_4|sf_looping, ["rain_1.ogg"]),
 ("money_received",sf_priority_10|sf_vol_6, ["coins_dropped_1.ogg"]),
 ("money_paid",sf_priority_10|sf_vol_10, ["coins_dropped_2.ogg"]),
 ("sword_clash_1", 0,["sword_clank_metal_09.ogg","sword_clank_metal_09b.ogg","sword_clank_metal_10.ogg","sword_clank_metal_10b.ogg","sword_clank_metal_12.ogg","sword_clank_metal_12b.ogg","sword_clank_metal_13.ogg","sword_clank_metal_13b.ogg"]),
 ("sword_clash_2", 0,["s_swordClash2.wav"]),
 ("sword_clash_3", 0,["s_swordClash3.wav"]),
 ("sword_swing", sf_vol_8|sf_priority_2,["s_swordSwing.wav"]),
 ("footstep_grass", sf_vol_4|sf_priority_1,["footstep_1.ogg","footstep_2.ogg","footstep_3.ogg","footstep_4.ogg"]),
 ("footstep_wood", sf_vol_6|sf_priority_1,["footstep_wood_1.ogg","footstep_wood_2.ogg","footstep_wood_4.ogg"]),
# ("footstep_wood", sf_vol_3|sf_priority_1,["footstep_stone_1.ogg","footstep_stone_3.ogg","footstep_stone_4.ogg"]),
 ("footstep_water", sf_vol_4|sf_priority_3,["water_walk_1.ogg","water_walk_2.ogg","water_walk_3.ogg","water_walk_4.ogg"]),
 ("footstep_horse",sf_priority_3, ["footstep_horse_5.ogg","footstep_horse_2.ogg","footstep_horse_3.ogg","footstep_horse_4.ogg"]),
# ("footstep_horse",0, ["s_footstep_horse_4b.wav","s_footstep_horse_4f.wav","s_footstep_horse_5b.wav","s_footstep_horse_5f.wav"]),
 ("footstep_horse_1b",sf_priority_3, ["s_footstep_horse_4b.wav","s_footstep_horse_4f.wav","s_footstep_horse_5b.wav","s_footstep_horse_5f.wav"]),
 ("footstep_horse_1f",sf_priority_3, ["s_footstep_horse_2b.wav","s_footstep_horse_2f.wav","s_footstep_horse_3b.wav","s_footstep_horse_3f.wav"]),
# ("footstep_horse_1f",sf_priority_3, ["footstep_horse_5.ogg","footstep_horse_2.ogg","footstep_horse_3.ogg","footstep_horse_4.ogg"]),
 ("footstep_horse_2b",sf_priority_3, ["s_footstep_horse_2b.wav"]),
 ("footstep_horse_2f",sf_priority_3, ["s_footstep_horse_2f.wav"]),
 ("footstep_horse_3b",sf_priority_3, ["s_footstep_horse_3b.wav"]),
 ("footstep_horse_3f",sf_priority_3, ["s_footstep_horse_3f.wav"]),
 ("footstep_horse_4b",sf_priority_3, ["s_footstep_horse_4b.wav"]),
 ("footstep_horse_4f",sf_priority_3, ["s_footstep_horse_4f.wav"]),
 ("footstep_horse_5b",sf_priority_3, ["s_footstep_horse_5b.wav"]),
 ("footstep_horse_5f",sf_priority_3, ["s_footstep_horse_5f.wav"]),
 ("jump_begin", sf_vol_7|sf_priority_9,["jump_begin.ogg"]),
 ("jump_end", sf_vol_5|sf_priority_9,["jump_end.ogg"]),
 ("jump_begin_water", sf_vol_4|sf_priority_9,["jump_begin_water.ogg"]),
 ("jump_end_water", sf_vol_4|sf_priority_9,["jump_end_water.ogg"]),
 ("horse_jump_begin", sf_vol_7|sf_priority_9,["horse_jump_begin.ogg"]),
 ("horse_jump_end", sf_vol_7|sf_priority_9,["horse_jump_end.ogg"]),
 ("horse_jump_begin_water", sf_vol_4|sf_priority_9,["jump_begin_water.ogg"]),
 ("horse_jump_end_water", sf_vol_4|sf_priority_9,["jump_end_water.ogg"]),

 ("release_bow",sf_vol_5, ["release_bow_1.ogg"]),
 ("release_crossbow",sf_vol_7, ["release_crossbow_1.ogg"]),
 ("throw_javelin",sf_vol_5, ["throw_javelin_2.ogg"]),
 ("throw_axe",sf_vol_7, ["throw_axe_1.ogg"]),
 ("throw_knife",sf_vol_5, ["throw_knife_1.ogg"]),
 ("throw_stone",sf_vol_7, ["throw_stone_1.ogg"]),

 ("reload_crossbow",sf_vol_3, ["reload_crossbow_1.ogg"]),
 ("reload_crossbow_continue",sf_vol_6, ["put_back_dagger.ogg"]),
 ("pull_bow",sf_vol_4, ["pull_bow_1.ogg"]),
 ("pull_arrow",sf_vol_5, ["pull_arrow.ogg"]),

 ("arrow_pass_by",0, ["arrow_pass_by_1.ogg","arrow_pass_by_2.ogg","arrow_pass_by_3.ogg","arrow_pass_by_4.ogg"]),
 ("bolt_pass_by",0, ["bolt_pass_by_1.ogg"]),
 ("javelin_pass_by",0, ["javelin_pass_by_1.ogg","javelin_pass_by_2.ogg"]),
 ("stone_pass_by",sf_vol_9, ["stone_pass_by_1.ogg"]),
 ("axe_pass_by",0, ["axe_pass_by_1.ogg"]),
 ("knife_pass_by",0, ["knife_pass_by_1.ogg"]),
 ("bullet_pass_by",0, ["arrow_whoosh_1.ogg"]),
 
 ("incoming_arrow_hit_ground",sf_priority_7|sf_vol_7, ["arrow_hit_ground_2.ogg","arrow_hit_ground_3.ogg","incoming_bullet_hit_ground_1.ogg"]),
 ("incoming_bolt_hit_ground",sf_priority_7|sf_vol_7, ["arrow_hit_ground_2.ogg","arrow_hit_ground_3.ogg","incoming_bullet_hit_ground_1.ogg"]),
 ("incoming_javelin_hit_ground",sf_priority_7|sf_vol_7, ["incoming_javelin_hit_ground_1.ogg"]),
 ("incoming_stone_hit_ground",sf_priority_7|sf_vol_7, ["incoming_stone_hit_ground_1.ogg"]),
 ("incoming_axe_hit_ground",sf_priority_7|sf_vol_7, ["incoming_javelin_hit_ground_1.ogg"]),
 ("incoming_knife_hit_ground",sf_priority_7|sf_vol_7, ["incoming_stone_hit_ground_1.ogg"]),
 ("incoming_bullet_hit_ground",sf_priority_7|sf_vol_7, ["incoming_bullet_hit_ground_1.ogg"]),

 ("outgoing_arrow_hit_ground",sf_priority_7|sf_vol_7, ["outgoing_arrow_hit_ground.ogg"]),
 ("outgoing_bolt_hit_ground",sf_priority_7|sf_vol_7,  ["outgoing_arrow_hit_ground.ogg"]),
 ("outgoing_javelin_hit_ground",sf_priority_7|sf_vol_10, ["outgoing_arrow_hit_ground.ogg"]),
 ("outgoing_stone_hit_ground",sf_priority_7|sf_vol_7, ["incoming_stone_hit_ground_1.ogg"]),
 ("outgoing_axe_hit_ground",sf_priority_7|sf_vol_7, ["incoming_javelin_hit_ground_1.ogg"]),
 ("outgoing_knife_hit_ground",sf_priority_7|sf_vol_7, ["incoming_stone_hit_ground_1.ogg"]),
 ("outgoing_bullet_hit_ground",sf_priority_7|sf_vol_7, ["incoming_bullet_hit_ground_1.ogg"]),


 ("draw_sword",sf_priority_4, ["draw_sword.ogg"]),
 ("put_back_sword",sf_priority_4, ["put_back_sword.ogg"]),
 ("draw_greatsword",sf_priority_4, ["draw_greatsword.ogg"]),
 ("put_back_greatsword",sf_priority_4, ["put_back_sword.ogg"]),
 ("draw_axe",sf_priority_4, ["draw_mace.ogg"]),
 ("put_back_axe",sf_priority_4, ["put_back_to_holster.ogg"]),
 ("draw_greataxe",sf_priority_4, ["draw_greataxe.ogg"]),
 ("put_back_greataxe",sf_priority_4, ["put_back_to_leather.ogg"]),
 ("draw_spear",sf_priority_4, ["draw_spear.ogg"]),
 ("put_back_spear",sf_priority_4, ["put_back_to_leather.ogg"]),
 ("draw_crossbow",sf_priority_4, ["draw_crossbow.ogg"]),
 ("put_back_crossbow",sf_priority_4, ["put_back_to_leather.ogg"]),
 ("draw_revolver",sf_priority_4, ["draw_from_holster.ogg"]),
 ("put_back_revolver",sf_priority_4, ["put_back_to_holster.ogg"]),
 ("draw_dagger",sf_priority_4, ["draw_dagger.ogg"]),
 ("put_back_dagger",sf_priority_4, ["put_back_dagger.ogg"]),
 ("draw_bow",sf_priority_4, ["draw_bow.ogg"]),
 ("put_back_bow",sf_priority_4, ["put_back_to_holster.ogg"]),
 ("draw_shield",sf_priority_4|sf_vol_7, ["draw_shield.ogg"]),
 ("put_back_shield",sf_priority_4|sf_vol_7, ["put_back_shield.ogg"]),
 ("draw_other",sf_priority_4, ["draw_other.ogg"]),
 ("put_back_other",sf_priority_4, ["draw_other2.ogg"]),

 ("body_fall_small",sf_priority_6|sf_vol_10, ["body_fall_small_1.ogg","body_fall_small_2.ogg"]),
 ("body_fall_big",sf_priority_6|sf_vol_10, ["body_fall_1.ogg","body_fall_2.ogg","body_fall_3.ogg"]),
# ("body_fall_very_big",sf_priority_9|sf_vol_10, ["body_fall_very_big_1.ogg"]),
 ("horse_body_fall_begin",sf_priority_6|sf_vol_10, ["horse_body_fall_begin_1.ogg"]),
 ("horse_body_fall_end",sf_priority_6|sf_vol_10, ["horse_body_fall_end_1.ogg","body_fall_2.ogg","body_fall_very_big_1.ogg"]),
 
## ("clang_metal",sf_priority_9, ["clang_metal_1.ogg","clang_metal_2.ogg","s_swordClash1.wav","s_swordClash2.wav","s_swordClash3.wav"]),
 ("hit_wood_wood",sf_priority_7|sf_vol_10, ["hit_wood_wood_1.ogg","hit_wood_wood_2.ogg","hit_wood_wood_3.ogg","hit_wood_wood_4.ogg","hit_wood_metal_4.ogg","hit_wood_metal_5.ogg","hit_wood_metal_6.ogg"]),#dummy
 ("hit_metal_metal",sf_priority_7|sf_vol_10, ["hit_metal_metal_3.ogg","hit_metal_metal_4.ogg",
                                              "hit_metal_metal_5.ogg","hit_metal_metal_6.ogg","hit_metal_metal_7.ogg","hit_metal_metal_8.ogg",
                                              "hit_metal_metal_9.ogg","hit_metal_metal_10.ogg",
                                              "clang_metal_1.ogg","clang_metal_2.ogg"]),
 ("hit_wood_metal",sf_priority_7|sf_vol_10, ["hit_metal_metal_1.ogg","hit_metal_metal_2.ogg","hit_wood_metal_7.ogg"]),
# ("clang_metal", sf_priority_9,["sword_clank_metal_09.ogg","sword_clank_metal_10.ogg","sword_clank_metal_12.ogg","sword_clank_metal_13.ogg"]),
## ("shield_hit_cut",sf_priority_5, ["shield_hit_cut_3.ogg","shield_hit_cut_4.ogg","shield_hit_cut_5.ogg"]),
 ("shield_hit_wood_wood",sf_priority_7|sf_vol_10, ["shield_hit_wood_wood_1.ogg","shield_hit_wood_wood_2.ogg","shield_hit_wood_wood_3.ogg"]),
 ("shield_hit_metal_metal",sf_priority_7|sf_vol_10, ["shield_hit_metal_metal_1.ogg","shield_hit_metal_metal_2.ogg","shield_hit_metal_metal_3.ogg","shield_hit_metal_metal_4.ogg"]),
 ("shield_hit_wood_metal",sf_priority_7|sf_vol_10, ["shield_hit_cut_3.ogg","shield_hit_cut_4.ogg","shield_hit_cut_5.ogg","shield_hit_cut_10.ogg"]), #(shield is wood)
 ("shield_hit_metal_wood",sf_priority_7|sf_vol_10, ["shield_hit_metal_wood_1.ogg","shield_hit_metal_wood_2.ogg","shield_hit_metal_wood_3.ogg"]),#(shield is metal)
 ("shield_broken",sf_priority_9, ["shield_broken.ogg"]),
 ("man_hit",sf_priority_7|sf_vol_10, ["man_hit_5.ogg","man_hit_6.ogg","man_hit_7.ogg","man_hit_8.ogg","man_hit_9.ogg","man_hit_10.ogg","man_hit_11.ogg","man_hit_12.ogg","man_hit_13.ogg","man_hit_14.ogg","man_hit_15.ogg",
                                      "man_hit_17.ogg","man_hit_18.ogg","man_hit_19.ogg","man_hit_22.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg","man_hit_59.ogg"]),
 ("man_die",sf_priority_10,  ["man_death_1.ogg","man_death_8.ogg","man_death_8b.ogg","man_death_11.ogg","man_death_14.ogg","man_death_16.ogg","man_death_18.ogg","man_death_21.ogg","man_death_29.ogg","man_death_40.ogg","man_death_44.ogg","man_death_46.ogg","man_death_48.ogg","man_death_64.ogg"]),# ["man_fall_1.ogg","man_fall_2.ogg","man_fall_3.ogg","man_fall_4.ogg"]),
 ("woman_hit",sf_priority_7, ["woman_hit_2.ogg","woman_hit_3.ogg",
                              "woman_hit_b_2.ogg","woman_hit_b_4.ogg","woman_hit_b_6.ogg","woman_hit_b_7.ogg","woman_hit_b_8.ogg",
                              "woman_hit_b_11.ogg","woman_hit_b_14.ogg","woman_hit_b_16.ogg"]),
 ("woman_die",sf_priority_10, ["woman_fall_1.ogg","woman_hit_b_5.ogg"]),
 ("hide",0, ["s_hide.wav"]),
 ("unhide",0, ["s_unhide.wav"]),
 ("neigh",0, ["horse_exterior_whinny_01.ogg","horse_exterior_whinny_02.ogg","horse_exterior_whinny_03.ogg","horse_exterior_whinny_04.ogg","horse_exterior_whinny_05.ogg","horse_whinny.ogg"]),
 ("gallop",sf_vol_3, ["horse_gallop_3.ogg","horse_gallop_4.ogg","horse_gallop_5.ogg"]),
 ("battle",sf_vol_4, ["battle.ogg"]),
# ("bow_shoot_player",sf_priority_10|sf_vol_10, ["bow_shoot_4.ogg"]),
# ("bow_shoot",sf_priority_4, ["bow_shoot_4.ogg"]),
# ("crossbow_shoot",sf_priority_4, ["bow_shoot_2.ogg"]),
 ("arrow_hit_body",sf_priority_4, ["arrow_hit_body_1.ogg","arrow_hit_body_2.ogg","arrow_hit_body_3.ogg"]),
 ("metal_hit_low_armor_low_damage",sf_priority_5|sf_vol_9, ["sword_hit_lo_armor_lo_dmg_1.ogg","sword_hit_lo_armor_lo_dmg_2.ogg","sword_hit_lo_armor_lo_dmg_3.ogg"]),
 ("metal_hit_low_armor_high_damage",sf_priority_5|sf_vol_9, ["sword_hit_lo_armor_hi_dmg_1.ogg","sword_hit_lo_armor_hi_dmg_2.ogg","sword_hit_lo_armor_hi_dmg_3.ogg"]),
 ("metal_hit_high_armor_low_damage",sf_priority_5|sf_vol_9, ["metal_hit_high_armor_low_damage.ogg","metal_hit_high_armor_low_damage_2.ogg","metal_hit_high_armor_low_damage_3.ogg"]),
 ("metal_hit_high_armor_high_damage",sf_priority_5|sf_vol_9, ["sword_hit_hi_armor_hi_dmg_1.ogg","sword_hit_hi_armor_hi_dmg_2.ogg","sword_hit_hi_armor_hi_dmg_3.ogg"]),
 ("wooden_hit_low_armor_low_damage",sf_priority_5|sf_vol_9, ["blunt_hit_low_1.ogg","blunt_hit_low_2.ogg","blunt_hit_low_3.ogg"]),
 ("wooden_hit_low_armor_high_damage",sf_priority_5|sf_vol_9, ["blunt_hit_high_1.ogg","blunt_hit_high_2.ogg","blunt_hit_high_3.ogg"]),
 ("wooden_hit_high_armor_low_damage",sf_priority_5|sf_vol_9, ["wooden_hit_high_armor_low_damage.ogg","wooden_hit_high_armor_low_damage_2.ogg"]),
 ("wooden_hit_high_armor_high_damage",sf_priority_5|sf_vol_9, ["blunt_hit_high_1.ogg","blunt_hit_high_2.ogg","blunt_hit_high_3.ogg"]),
 ("blunt_hit",sf_priority_5|sf_vol_9, ["punch_1.ogg","punch_4.ogg","punch_4.ogg","punch_5.ogg"]),
 ("player_hit_by_arrow",sf_priority_10|sf_vol_10, ["player_hit_by_arrow.ogg"]),
 ("pistol_shot",sf_priority_10|sf_vol_10, ["fl_pistol.wav"]),
 ("man_grunt",sf_priority_6|sf_vol_4, ["man_excercise_1.ogg","man_excercise_2.ogg","man_excercise_4.ogg"]),
 ("man_breath_hard",sf_priority_3|sf_vol_8, ["man_ugh_1.ogg","man_ugh_2.ogg","man_ugh_4.ogg","man_ugh_7.ogg","man_ugh_12.ogg","man_ugh_13.ogg","man_ugh_17.ogg"]),
 ("man_grunt_long",sf_priority_5|sf_vol_8, ["man_grunt_1.ogg","man_grunt_2.ogg","man_grunt_3.ogg","man_grunt_5.ogg","man_grunt_13.ogg","man_grunt_14.ogg"]),
 ("man_yell",sf_priority_6|sf_vol_8, ["man_yell_4.ogg","man_yell_4_2.ogg","man_yell_7.ogg","man_yell_9.ogg","man_yell_11.ogg","man_yell_13.ogg","man_yell_15.ogg","man_yell_16.ogg","man_yell_17.ogg","man_yell_20.ogg","man_shortyell_4.ogg","man_shortyell_5.ogg","man_shortyell_6.ogg","man_shortyell_9.ogg","man_shortyell_11.ogg","man_shortyell_11b.ogg",
                        "man_yell_b_18.ogg","man_yell_22.ogg","man_yell_b_21.ogg","man_yell_b_22.ogg","man_yell_b_23.ogg","man_yell_c_20.ogg"]),
#TODONOW:
 ("man_warcry",sf_priority_6, ["man_insult_2.ogg","man_insult_3.ogg","man_insult_7.ogg","man_insult_9.ogg","man_insult_13.ogg","man_insult_15.ogg","man_insult_16.ogg"]),

 ("encounter_looters",sf_2d|sf_vol_5, ["encounter_river_pirates_5.ogg","encounter_river_pirates_6.ogg","encounter_river_pirates_9.ogg","encounter_river_pirates_10.ogg","encounter_river_pirates_4.ogg"]),

 ("encounter_bandits",sf_2d|sf_vol_5, ["encounter_bandit_2.ogg","encounter_bandit_9.ogg","encounter_bandit_12.ogg","encounter_bandit_13.ogg","encounter_bandit_15.ogg","encounter_bandit_16.ogg","encounter_bandit_10.ogg",]),
 ("encounter_farmers",sf_2d|sf_vol_5, ["encounter_farmer_2.ogg","encounter_farmer_5.ogg","encounter_farmer_7.ogg","encounter_farmer_9.ogg"]),
 ("encounter_sea_raiders",sf_2d|sf_vol_5, ["encounter_sea_raider_5.ogg","encounter_sea_raider_9.ogg","encounter_sea_raider_9b.ogg","encounter_sea_raider_10.ogg"]),
 ("encounter_steppe_bandits",sf_2d|sf_vol_5, ["encounter_steppe_bandit_3.ogg","encounter_steppe_bandit_3b.ogg","encounter_steppe_bandit_8.ogg","encounter_steppe_bandit_10.ogg","encounter_steppe_bandit_12.ogg"]),
 ("encounter_nobleman",sf_2d|sf_vol_5, ["encounter_nobleman_1.ogg"]),
 ("encounter_vaegirs_ally",sf_2d|sf_vol_5, ["encounter_vaegirs_ally.ogg","encounter_vaegirs_ally_2.ogg"]),
 ("encounter_vaegirs_neutral",sf_2d|sf_vol_5, ["encounter_vaegirs_neutral.ogg","encounter_vaegirs_neutral_2.ogg","encounter_vaegirs_neutral_3.ogg","encounter_vaegirs_neutral_4.ogg"]),
 ("encounter_vaegirs_enemy",sf_2d|sf_vol_5, ["encounter_vaegirs_neutral.ogg","encounter_vaegirs_neutral_2.ogg","encounter_vaegirs_neutral_3.ogg","encounter_vaegirs_neutral_4.ogg"]),
 ("sneak_town_halt",sf_2d, ["sneak_halt_1.ogg","sneak_halt_2.ogg"]),
 ("horse_walk",sf_priority_3|sf_vol_9, ["horse_walk_1.ogg","horse_walk_2.ogg","horse_walk_3.ogg","horse_walk_4.ogg"]),
 ("horse_trot",sf_priority_3|sf_vol_4, ["horse_trot_1.ogg","horse_trot_2.ogg","horse_trot_3.ogg","horse_trot_4.ogg"]),
 ("horse_canter",sf_priority_3|sf_vol_6, ["horse_canter_1.ogg","horse_canter_2.ogg","horse_canter_3.ogg","horse_canter_4.ogg"]),
 ("horse_gallop",sf_priority_3|sf_vol_8, ["horse_gallop_6.ogg","horse_gallop_7.ogg","horse_gallop_8.ogg","horse_gallop_9.ogg"]),
 ("horse_breath",sf_priority_3|sf_vol_10, ["horse_breath_4.ogg","horse_breath_5.ogg","horse_breath_6.ogg","horse_breath_7.ogg"]),
 ("horse_snort",sf_priority_5|sf_vol_7, ["horse_snort_1.ogg","horse_snort_2.ogg","horse_snort_3.ogg","horse_snort_4.ogg","horse_snort_5.ogg"]),
 ("horse_low_whinny",sf_vol_9, ["horse_whinny-1.ogg","horse_whinny-2.ogg"]),
 ("block_fist",0, ["block_fist_3.ogg","block_fist_4.ogg"]),
 ("man_hit_blunt_weak",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_blunt_strong",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_pierce_weak",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_pierce_strong",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_cut_weak",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_cut_strong",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_victory",sf_priority_5|sf_vol_10, ["man_victory_3.ogg","man_victory_4.ogg","man_victory_5.ogg","man_victory_8.ogg","man_victory_15.ogg","man_victory_49.ogg","man_victory_52.ogg","man_victory_54.ogg","man_victory_57.ogg","man_victory_71.ogg"]),
 ("fire_loop",sf_priority_9|sf_vol_4|sf_looping|sf_start_at_random_pos, ["Fire_Torch_Loop3.ogg"]),
 ("torch_loop",sf_priority_9|sf_vol_4|sf_looping|sf_start_at_random_pos, ["Fire_Torch_Loop3.ogg"]),
 ("dummy_hit",sf_priority_9, ["shield_hit_cut_3.ogg","shield_hit_cut_5.ogg"]),
 ("dummy_destroyed",sf_priority_9, ["shield_broken.ogg"]),
 ("gourd_destroyed",sf_priority_9, ["shield_broken.ogg"]),#TODO
 ("cow_moo", sf_2d|sf_priority_9|sf_vol_8, ["cow_moo_1.ogg"]),
 ("cow_slaughter", sf_2d|sf_priority_9|sf_vol_8, ["cow_slaughter.ogg"]),
 ("distant_dog_bark", sf_2d|sf_priority_8|sf_vol_8, ["d_dog1.ogg","d_dog2.ogg","d_dog3.ogg","d_dog7.ogg"]),
 ("distant_owl", sf_2d|sf_priority_8|sf_vol_9, ["d_owl2.ogg","d_owl3.ogg","d_owl4.ogg"]),
 ("distant_chicken", sf_2d|sf_priority_8|sf_vol_8, ["d_chicken1.ogg","d_chicken2.ogg"]),
 ("distant_carpenter", sf_2d|sf_priority_8|sf_vol_3, ["d_carpenter1.ogg","d_saw_short3.ogg"]),
 ("distant_blacksmith", sf_2d|sf_priority_8|sf_vol_4, ["d_blacksmith2.ogg"]),
 ("arena_ambiance", sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["arena_loop11.ogg"]),
 ("town_ambiance", sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["town_loop_3.ogg"]),

#TLD start

#tf_male         = 0	# (Dale/Northmen/corsair/bandits)
#tf_female       = 1	# all factions
#tf_gondor		= 2
 ("gondor_yell",sf_priority_6|sf_vol_8, ["gondor_yell_1.mp3","gondor_yell_2.mp3","gondor_yell_3.mp3","gondor_yell_4.mp3","gondor_yell_5.mp3","gondor_yell_6.mp3"]),
 ("gondor_victory",sf_priority_5|sf_vol_10, ["gondor_victory_1.mp3","gondor_victory_2.mp3","gondor_victory_3.mp3","gondor_victory_4.mp3","gondor_victory_5.mp3","gondor_victory_6.mp3"]),
#tf_rohan		= 3
 ("rohan_yell",sf_priority_6|sf_vol_8, ["rohan_yell_1.mp3","rohan_yell_2.mp3","rohan_yell_3.mp3","rohan_yell_4.mp3","rohan_yell_5.mp3","rohan_yell_6.mp3","rohan_yell_7.mp3","rohan_yell_8.mp3","rohan_yell_9.mp3","rohan_yell_10.mp3","rohan_yell_11.mp3","rohan_yell_12.mp3","rohan_yell_13.mp3","rohan_yell_14.mp3"]),
 ("rohan_victory",sf_priority_5|sf_vol_10, ["rohan_victory_1.mp3","rohan_victory_2.mp3","rohan_victory_3.mp3","rohan_victory_4.mp3"]),
#tf_dunland	= 4
 ("dunlender_yell",sf_priority_6|sf_vol_8, ["dun_yell_1.mp3","dun_yell_2.mp3","dun_yell_3.mp3","dun_yell_4.mp3","dun_yell_5.mp3","dun_yell_6.mp3","dun_yell_7.mp3","dun_yell_8.mp3","dun_yell_9.mp3","dun_yell_10.mp3","dun_yell_11.mp3","dun_yell_12.mp3","dun_yell_13.mp3","dun_yell_14.mp3","dun_yell_15.mp3","dun_yell_16.mp3","dun_yell_17.mp3","dun_yell_18.mp3","dun_yell_19.mp3","dun_yell_20.mp3","dun_yell_21.mp3","dun_yell_22.mp3","dun_yell_23.mp3","dun_yell_24.mp3"]),
 ("dunlender_victory",sf_priority_5|sf_vol_10, ["dun_victory_1.mp3","dun_victory_2.mp3","dun_victory_3.mp3","dun_victory_4.mp3","dun_victory_5.mp3","dun_victory_6.mp3","dun_victory_7.mp3","dun_victory_8.mp3","dun_victory_9.mp3"]),


#tf_orc			= 5 #(orcs, goblins)
 ("orc_die",sf_priority_10,  ["orc_death_1.mp3","orc_death_2.mp3","orc_death_3.mp3","orc_death_4.mp3","orc_death_5.mp3","orc_death_6.mp3","orc_death_7.mp3","orc_death_8.mp3"]),
 ("orc_hit",sf_priority_7|sf_vol_10, ["orc_hit_1.mp3","orc_hit_2.mp3","orc_hit_3.mp3","orc_hit_4.mp3","orc_hit_6.mp3","orc_hit_7.mp3","orc_hit_9.mp3","orc_hit_10.mp3"]),
 ("orc_grunt",sf_priority_6|sf_vol_4, ["orc_grunt_1.mp3"]), 
 ("orc_grunt_long",sf_priority_5|sf_vol_8, ["orc_grunt_long_1.mp3"]), 
 ("orc_yell",sf_priority_6|sf_vol_8, ["orc_yell_1.mp3","orc_yell_2.mp3"]), 
 ("orc_victory",sf_priority_5|sf_vol_10, ["orc_victory_1.mp3","orc_victory_2.mp3","orc_victory_3.mp3","orc_victory_4.mp3","orc_victory_5.mp3","orc_victory_6.mp3"]), 
 #tf_uruk			= 6 #(Uruks, Uruk Hai)
#tf_harad	= 7
 ("haradrim_yell",sf_priority_6|sf_vol_8, ["har_yell_1.mp3","har_yell_2.mp3","har_yell_3.mp3","har_yell_4.mp3","har_yell_5.mp3","har_yell_6.mp3","har_yell_7.mp3","har_yell_8.mp3","har_yell_9.mp3","har_yell_10.mp3"]),
 ("haradrim_victory",sf_priority_5|sf_vol_10, ["haradrim_victory_1.mp3","haradrim_victory_2.mp3","haradrim_victory_3.mp3","haradrim_victory_4.mp3","haradrim_victory_5.mp3"]),
 ("haradrim_die",sf_priority_10,  ["wilhelm.ogg","man_death_8.ogg","man_death_8b.ogg","man_death_11.ogg","man_death_14.ogg","man_death_16.ogg","man_death_18.ogg","man_death_21.ogg","man_death_29.ogg","man_death_40.ogg","man_death_44.ogg","man_death_46.ogg","man_death_48.ogg","man_death_64.ogg"]),# ["man_fall_1.ogg","man_fall_2.ogg","man_fall_3.ogg","man_fall_4.ogg"]),
#tf_easterling	= 8 #(Rhun/khand)
#tf_dwarf		= 9
#tf_troll		= 10
 ("troll_die",sf_priority_10,  ["troll_death_1.mp3"]),
 ("troll_hit",sf_priority_7|sf_vol_10, ["troll_hit_1.mp3","troll_hit_1.mp3","troll_hit_1.mp3"]), 
 ("troll_grunt",sf_priority_6|sf_vol_4, ["troll_grunt_1.mp3","troll_grunt_2.mp3"]), 
 ("troll_grunt_long",sf_priority_5|sf_vol_8, ["troll_grunt_2.mp3","troll_hit_2.mp3"]), 
 ("troll_yell",sf_priority_6|sf_vol_8, ["troll_grunt_2.mp3","troll_hit_2.mp3"]), 
 ("troll_victory",sf_priority_5|sf_vol_10, ["troll_grunt_2.mp3","troll_hit_2.mp3","troll_death_1.mp3"]), 
 #troll_grunt_long = grunt, yell = grunt, 
#tf_dunedain		= 11
 ("dunedain_yell",sf_priority_6|sf_vol_8, ["dunedain_yell_1.mp3","dunedain_yell_2.mp3","dunedain_yell_3.mp3","dunedain_yell_4.mp3","dunedain_yell_5.mp3","dunedain_yell_6.mp3","dunedain_yell_7.mp3","dunedain_yell_8.mp3","dunedain_yell_9.mp3","dunedain_yell_10.mp3"]),
 ("dunedain_victory",sf_priority_5|sf_vol_10, ["dunedain_victory_1.mp3","dunedain_victory_2.mp3","dunedain_victory_3.mp3"]),
#tf_lorien	= 12
 ("lothlorien_yell",sf_priority_6|sf_vol_8, ["elf_lothlorien_yell_1.mp3","elf_lothlorien_yell_2.mp3","elf_lothlorien_yell_3.mp3","elf_basic_yell_1.mp3","elf_basic_yell_2.mp3","elf_basic_yell_3.mp3","elf_basic_yell_4.mp3","elf_basic_yell_5.mp3","elf_basic_yell_6.mp3","elf_basic_yell_7.mp3","elf_basic_yell_8.mp3","elf_basic_yell_9.mp3","elf_basic_yell_10.mp3"]),
 ("lothlorien_victory",sf_priority_5|sf_vol_10, ["elf_basic_victory_1.mp3","elf_basic_victory_2.mp3","elf_basic_victory_3.mp3","elf_basic_victory_4.mp3","elf_basic_victory_5.mp3"]),  
#tf_imladris	= 13
 ("rivendell_yell",sf_priority_6|sf_vol_8, ["elf_rivendell_yell_1.mp3","elf_rivendell_yell_2.mp3","elf_basic_yell_1.mp3","elf_basic_yell_2.mp3","elf_basic_yell_3.mp3","elf_basic_yell_4.mp3","elf_basic_yell_5.mp3","elf_basic_yell_6.mp3","elf_basic_yell_7.mp3","elf_basic_yell_8.mp3","elf_basic_yell_9.mp3","elf_basic_yell_10.mp3"]),
 ("rivendell_victory",sf_priority_5|sf_vol_10, ["elf_basic_victory_1.mp3","elf_basic_victory_2.mp3","elf_basic_victory_3.mp3","elf_basic_victory_4.mp3","elf_basic_victory_5.mp3"]),  
 #tf_woodelf		= 14
 ("mirkwood_yell",sf_priority_6|sf_vol_8, ["elf_mirkwood_yell_1.mp3","elf_mirkwood_yell_2.mp3","elf_basic_yell_1.mp3","elf_basic_yell_2.mp3","elf_basic_yell_3.mp3","elf_basic_yell_4.mp3","elf_basic_yell_5.mp3","elf_basic_yell_6.mp3","elf_basic_yell_7.mp3","elf_basic_yell_8.mp3","elf_basic_yell_9.mp3","elf_basic_yell_10.mp3"]),
 ("mirkwood_victory",sf_priority_5|sf_vol_10, ["elf_basic_victory_1.mp3","elf_basic_victory_2.mp3","elf_basic_victory_3.mp3","elf_basic_victory_4.mp3","elf_basic_victory_5.mp3"]),  
#tf_evil_male	= 15

 ("big_weapon_swing", sf_vol_10|sf_priority_7,["s_big_weaponSwing.wav"]),

 ("thunder",sf_priority_10|sf_vol_10, ["thunder.ogg"]),
 ("pull_ballista",sf_vol_8, ["pull_bow_1.ogg"]),
 ("evil_orders",sf_vol_3, ["order_form_ranks_(orc).mp3"]),
 ("evil_horn",sf_vol_10, ["horn_isengard.ogg"]),

 ("nazgul_skreech_long",sf_priority_10|sf_vol_10, ["nazgul_02.mp3"]),
 ("nazgul_skreech_short",sf_priority_10|sf_vol_10, ["nazgul_01.mp3"]),

 ("horror_scream_man"  ,sf_priority_10|sf_vol_10,["horror_scream_man_0.wav","horror_scream_man_1.wav","horror_scream_man_2.wav","horror_scream_man_3.wav","horror_scream_man_4.wav"]),
 ("horror_scream_woman",sf_priority_10|sf_vol_10,["horror_scream_woman.wav"]),
 ("horror_scream_orc"  ,sf_priority_10|sf_vol_10,["horror_scream_orc.wav"]),
 
 ("warg_lone_woof",sf_priority_6|sf_vol_10, ["warg_bark01.mp3","warg_bark02.mp3","warg_bark03.mp3","warg_growl01.mp3","warg_howl01.mp3"
											   #,"warg_howl02.mp3","warg_howl03.mp3"
											   ]),
 ("horse_snort_again",sf_priority_5|sf_vol_7, ["horse_snort_1.ogg","horse_snort_2.ogg","horse_snort_3.ogg","horse_snort_4.ogg","horse_snort_5.ogg"]),

 ("spear_trap",sf_priority_7|sf_vol_9, ["spear_trap.wav"]),

 ("moria_ambiance"           ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["moria_loop.ogg"]),
 ("henneth_ambiance"         ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["henneth_loop.ogg"]),
 ("goodforest_ambiance"      ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["good_forest_loop.ogg"]),
 ("evilforest_ambiance"      ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["evil_forest_loop.ogg"]),
 ("water_waves_ambiance"     ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["water_waves_loop.ogg"]),
 ("water_splash_ambiance"    ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["water_splash_loop.ogg"]),
 ("water_wavesplash_ambiance",sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["water_wavesplash_loop.ogg"]),
 ("wind_ambiance"            ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["wind_loop.ogg"]),
 ("isengard_ambiance"        ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["isen_loop.ogg"]),
 ("evilmen_ambiance"         ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["evil_men_loop.ogg"]),
 ("orcs_ambiance"            ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["beast_loop.ogg"]),
 ("morgul_ambiance"          ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["morgul_loop.ogg"]),
 ("gondor_ambiance"          ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["gondor_people_loop.ogg"]),
 ("rohan_ambiance"           ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["rohan_people_loop.ogg"]),
 ("dwarf_ambiance"           ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["dwarf_men_loop.ogg"]),
 ("harad_ambiance"           ,sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["harad_loop.ogg"]),

("gondor_occasional"  ,sf_2d|sf_priority_8|sf_vol_4,["good_eagle01.ogg","gondor_army.ogg","d_blacksmith2.ogg","good_workshop.ogg","d_dog7.ogg"]),
("elves_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["good_bird01.ogg","good_bird02.ogg","good_bird03.ogg","good_bird_wings.ogg"]), 
("beorn_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["good_bird01.ogg","good_bird02.ogg","good_bird03.ogg","good_workshop.ogg","d_saw_short3.ogg","d_dog7.ogg","d_carpenter1.ogg"]), 
("rohan_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["rohan01.ogg", "rohan02.ogg","rohan03.ogg","rohan04.ogg","good_workshop.ogg", "good_eagle01.ogg","good_bird01.ogg","d_blacksmith2.ogg","d_dog7.ogg","d_chicken1.ogg"]),
("dwarf_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["dwarves01.ogg", "dwarves02.ogg","d_blacksmith2.ogg","osgiliath05.ogg","osgiliath02.ogg"]),
("dale_occasional"    ,sf_2d|sf_priority_8|sf_vol_4,["good_bird01.ogg","good_bird02.ogg","good_bird03.ogg","good_workshop.ogg","d_saw_short3.ogg", "d_blacksmith2.ogg","d_dog7.ogg","d_chicken1.ogg","osgiliath04.ogg"]),
("rhun_occasional"    ,sf_2d|sf_priority_8|sf_vol_4,["rohan01.ogg", "rohan02.ogg","rohan03.ogg","rohan04.ogg","evil_crow.ogg", "d_saw_short3.ogg","d_blacksmith2.ogg","d_dog7.ogg"]),
("harad_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["d_chicken1.ogg", "rohan02.ogg","rohan03.ogg","rohan04.ogg","evil_crow.ogg", "d_saw_short3.ogg","d_chicken2.ogg","harad01.ogg","harad02.ogg","harad03.ogg"]),
("umbar_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["silence.ogg","sea_seagulls.ogg", "sea_seaside.ogg"]),
("dunland_occasional" ,sf_2d|sf_priority_8|sf_vol_4,["evil_crow.ogg", "good_eagle01.ogg","d_dog1.ogg","d_dog2.ogg","d_dog3.ogg","d_dog7.ogg","d_carpenter1.ogg"]),
("orc_occasional"     ,sf_2d|sf_priority_8|sf_vol_4,["evil_flies_loop.ogg","evil_crow.ogg", "orc_warg.ogg","orc_beast01.ogg","orc_beast02.ogg","orc_beast03.ogg"]),
("guldur_occasional"  ,sf_2d|sf_priority_8|sf_vol_4,["evil_crow.ogg","orc_beast01.ogg","orc_beast02.ogg","orc_beast03.ogg"]),
("moria_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["silence.ogg","silence.ogg","moria01.ogg","moria02.ogg"]),
("isengard_occasional",sf_2d|sf_priority_8|sf_vol_4,["moria02.ogg", "evil_crow.ogg","orc_beast01.ogg","orc_beast02.ogg","orc_beast03.ogg", "d_saw_short3.ogg","orc_warg.ogg","d_blacksmith2.ogg","dwarves01.ogg","dwarves02.ogg","osgiliath04.ogg","d_carpenter1.ogg"]),
("urukhai_occasional" ,sf_2d|sf_priority_8|sf_vol_4,["evil_crow.ogg","orc_beast01.ogg","orc_beast02.ogg","orc_beast03.ogg", "orc_warg.ogg","d_carpenter1.ogg"]),
("seaside_occasional" ,sf_2d|sf_priority_8|sf_vol_4,["good_bird01.ogg","good_bird02.ogg","good_bird03.ogg","sea_seagulls.ogg", "sea_seaside.ogg", "d_blacksmith2.ogg"]),
("morgul_occasional"  ,sf_2d|sf_priority_8|sf_vol_4,["silence.ogg","silence.ogg","silence.ogg","silence.ogg","silence.ogg","silence.ogg","silence.ogg","morgul01.ogg","morgul02.ogg"]),
("eosgi_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["orc_beast01.ogg","orc_beast02.ogg","orc_beast03.ogg","osgiliath01.ogg","osgiliath02.ogg","osgiliath03.ogg","osgiliath04.ogg","osgiliath05.ogg"]),
("wosgi_occasional"   ,sf_2d|sf_priority_8|sf_vol_4,["osgiliath01.ogg","osgiliath02.ogg","osgiliath03.ogg","osgiliath04.ogg","osgiliath05.ogg"]),
 ##TLD end 
 
]
