simple_triggers_file version 1

simple_triggers = [

(ti_on_party_encounter ,[
(store_encountered_party, "$g_encountered_party"),
(store_encountered_party2, "$g_encountered_party_2"),
(assign, "$talk_context", 0),
(assign, "$g_player_surrenders", 0),
(assign, "$g_enemy_surrenders", 0),
(assign, "$g_leave_encounter", 0),
(assign, "$new_encounter", 1),
(try_begin),
    (neg|ge, "$g_encountered_party_2", 0),
    (try_begin),
        (eq, "$g_encountered_party", "p_town_4"),
        (try_begin),
            (eq, "$gondor_status", 0),
            (jump_to_menu, "menu_gondor_fallen"),
        (else_try),
            (neg|eq, "$gondor_status", 0),
            (jump_to_menu, "menu_castle_outside_dol_amroth"),
        (try_end),
    (else_try),
        (is_between, "$g_encountered_party", "p_town_11", "p_castle_1"),
        (try_begin),
            (eq, "$rohan_status", 0),
            (jump_to_menu, "menu_rohan_fallen"),
        (else_try),
            (neg|eq, "$rohan_status", 0),
            (jump_to_menu, "menu_castle_outside_b"),
        (try_end),
    (else_try),
        (is_between, "$g_encountered_party", "p_town_1", "p_town_11"),
        (try_begin),
            (eq, "$gondor_status", 0),
            (jump_to_menu, "menu_gondor_fallen"),
        (else_try),
            (neg|eq, "$gondor_status", 0),
            (jump_to_menu, "menu_castle_outside"),
        (try_end),
    (else_try),(eq, "$g_encountered_party", "p_zendar"),(jump_to_menu, "menu_zendar"),
    (else_try),(eq, "$g_encountered_party", "p_salt_mine"),(jump_to_menu, "menu_salt_mine"),
    (else_try),(eq, "$g_encountered_party", "p_dhorak_keep"),(jump_to_menu, "menu_dhorak_keep"),
    (else_try),(eq, "$g_encountered_party", "p_four_ways_inn"),(jump_to_menu, "menu_four_ways_inn"),
    (else_try),(eq, "$g_encountered_party", "p_training_ground"),(jump_to_menu, "menu_training_ground"),
    (else_try),(eq, "$g_encountered_party", "p_eastfold_inn"),(jump_to_menu, "menu_eastfold_inn"),
    (else_try),(eq, "$g_encountered_party", "p_isengard"),(jump_to_menu, "menu_Isengard"),
    (else_try),(eq, "$g_encountered_party", "p_morannon"),(jump_to_menu, "menu_Morannon"),
    (else_try),(eq, "$g_encountered_party", "p_minas_morgul"),(jump_to_menu, "menu_Minas_Morgul"),
    (else_try),(eq, "$g_encountered_party", "p_osgiliath"),(jump_to_menu, "menu_Osgiliath"),
    (else_try),(eq, "$g_encountered_party", "p_moria"),(jump_to_menu, "menu_Moria"),
    (else_try),(eq, "$g_encountered_party", "p_dol_guldur"),(jump_to_menu, "menu_Dol_Guldur"),
    (else_try),(eq, "$g_encountered_party", "p_haradrim_camp"),(jump_to_menu, "menu_haradrim_camp"),
    (else_try),(eq, "$g_encountered_party", "p_corsair_camp"),(jump_to_menu, "menu_corsair_camp"),
    (else_try),(eq, "$g_encountered_party", "p_easterling_north_camp"),(jump_to_menu, "menu_easterling_north_camp"),
    (else_try),(eq, "$g_encountered_party", "p_easterling_south_camp"),(jump_to_menu, "menu_easterling_south_camp"),
    (else_try),(eq, "$g_encountered_party", "p_dunlander_camp"),(jump_to_menu, "menu_dunlander_camp"),
    (else_try),(eq, "$g_encountered_party", "p_orc_sentry_camp"),(jump_to_menu, "menu_orc_sentry_camp"),
    (else_try),(eq, "$g_encountered_party", "p_uruk_hai_outpost"),(jump_to_menu, "menu_uruk_hai_outpost"),
    (else_try),(eq, "$g_encountered_party", "p_uruk_hai_hunting_camp"),(jump_to_menu, "menu_uruk_hai_hunting_camp"),
    (else_try),(eq, "$g_encountered_party", "p_uruk_hai_river_camp"),(jump_to_menu, "menu_uruk_hai_river_camp"),
    (else_try),(eq, "$g_encountered_party", "p_caras_galadhon"),(jump_to_menu, "menu_caras_galadhon"),
    (else_try),(eq, "$g_encountered_party", "p_cerin_amroth"),(jump_to_menu, "menu_cerin_amroth"),
    (else_try),(eq, "$g_encountered_party", "p_cerin_dolen"),(jump_to_menu, "menu_cerin_dolen"),
    (else_try),(eq, "$g_encountered_party", "p_rivendell_elf_camp"),(jump_to_menu, "menu_rivendell_elf_camp"),
    (else_try),(eq, "$g_encountered_party", "p_woodelf_camp"),(jump_to_menu, "menu_woodelf_camp"),
    (else_try),(eq, "$g_encountered_party", "p_henneth_annun"),(jump_to_menu, "menu_henneth_annun"),
    (else_try),(eq, "$g_encountered_party", "p_anduin_river_village"),(jump_to_menu, "menu_anduin_river_village"),
    (else_try),(eq, "$g_encountered_party", "p_limlight_river_village"),(jump_to_menu, "menu_limlight_river_village"),
    (else_try),(eq, "$g_encountered_party", "p_hill_folk_village"),(jump_to_menu, "menu_hill_folk_village"),
    (else_try),(eq, "$g_encountered_party", "p_woodsman_village"),(jump_to_menu, "menu_woodsman_village"),
    (else_try),(eq, "$g_encountered_party", "p_ancient_ruins"),(jump_to_menu, "menu_ancient_ruins"),
    (else_try),(eq, "$g_encountered_party", "p_cair_andros"),(jump_to_menu, "menu_cair_andros"),
    (else_try),(eq, "$g_encountered_party", "p_cirith_ungol"),(jump_to_menu, "menu_cirith_ungol"),
    (else_try),(is_between, "$g_encountered_party", "p_mound_of_mablung", "p_end_mounds"),(jump_to_menu, "menu_burial_mound"),
    (else_try),(eq, "$g_encountered_party", "p_pyre_of_duessa"),(jump_to_menu, "menu_funeral_pyre_female"),
    (else_try),(is_between, "$g_encountered_party", "p_start_pyres", "p_end_pyres"),(jump_to_menu, "menu_funeral_pyre"),
    (else_try),(eq, "$g_encountered_party", "p_barad_dur"),(jump_to_menu, "menu_barad-dur"),
	(else_try),(eq, "$g_encountered_party", "p_old_ford"),(jump_to_menu, "menu_camp"),
    (else_try),(jump_to_menu, "menu_simple_encounter"),
    (try_end),
(else_try),
    (try_begin),
        (this_or_next|is_between, "$g_encountered_party", "p_town_1", "p_castle_1"),
        (is_between, "$g_encountered_party", "p_castle_1", "p_castle_8"),
        (try_begin),
            (store_faction_of_party, ":faction", "$g_encountered_party"),
            (eq, ":faction", "fac_gondor"),
            (eq, "$gondor_status", 0),
            (jump_to_menu, "menu_gondor_fallen"),
        (else_try),
            (store_faction_of_party, ":faction", "$g_encountered_party"),
            (eq, ":faction", "fac_rohan"),
            (eq, "$rohan_status", 0),
            (jump_to_menu, "menu_rohan_fallen"),
        (else_try),
            (eq, "$auto_enter_town", "$g_encountered_party"),
            (is_between, "$g_encountered_party", "p_town_11", "p_castle_1"),
            (jump_to_menu, "menu_town_b"),
        (else_try),
            (eq, "$auto_enter_town", "$g_encountered_party"),
            (eq, "$g_encountered_party", "$dol_amroth"),
            (jump_to_menu, "menu_town_dol_amroth"),
        (else_try),
            (eq, "$auto_enter_town", "$g_encountered_party"),
            (is_between, "$g_encountered_party", "p_town_1", "p_town_11"),
            (jump_to_menu, "menu_town"),
        (try_end),
    (else_try),
        (jump_to_menu, "menu_pre_join"),
    (try_end),
(try_end),
(assign, "$auto_enter_town", 0),
],

(ti_simulate_battle ,[
(eq, "$abstract_combat_system", 0),
(store_trigger_param_1, ":ally"),
(store_trigger_param_2, ":enemy"),
(party_collect_attachments_to_party, ":ally", "p_collective_ally"),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_count_fit_regulars", "p_collective_ally"),
(store_div, ":local2", reg0, 20),
(val_add, ":local2", 1),
(call_script, "script_party_count_fit_regulars", "p_collective_enemy"),
(store_div, ":local3", reg0, 20),
(val_add, ":local3", 1),
(inflict_casualties_to_party_group, ":enemy", ":local2", "p_temp_casualties"),
(call_script, "script_map_hero_status_in_abstract_battle"),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_calculate_regular_strength", "p_collective_enemy", 0),
(assign, ":local4", reg0),
(try_begin),
    (gt, ":local4", 0),
    (inflict_casualties_to_party_group, ":ally", ":local3", "p_temp_casualties"),
    (call_script, "script_map_hero_status_in_abstract_battle"),
(try_end),
(party_collect_attachments_to_party, ":ally", "p_collective_ally"),
(call_script, "script_party_calculate_regular_strength", "p_collective_ally"),
(assign, ":local5", reg0),
(try_begin),
    (this_or_next|eq, ":local4", 0),
    (eq, ":local5", 0),
    (try_begin),
        (eq, ":local4", 0),
        (assign, ":winner", ":ally"),
        (assign, ":loser", ":enemy"),
        (assign, ":local8", "p_collective_enemy"),
    (else_try),
        (assign, ":winner", ":enemy"),
        (assign, ":loser", ":ally"),
        (assign, ":local8", "p_collective_ally"),
    (try_end),
    (call_script, "script_get_nonempty_party_in_group", ":winner"),
    (assign, ":local9", reg0),
    (ge, ":local9", 0),
#    (store_faction_of_party, ":local10", ":local9"),
#    (store_faction_of_party, ":local11", ":loser"),
    (party_clear, "p_temp_party"),
    (assign, "$g_move_heroes", 0),
    (call_script, "script_party_add_party_prisoners", "p_temp_party", ":local8"),
    (assign, "$map_hero_root_defender_party", ":ally"),
    (assign, "$map_hero_root_attacker_party", ":enemy"),
    (call_script, "script_party_prisoners_add_party_companions", "p_temp_party", ":local8"),
    (distribute_party_among_party_group, "p_temp_party", ":winner"),
    (call_script, "script_clear_party_group", ":loser"),
    (set_trigger_result, 1),
    (try_begin),
        (eq, ":loser", 0),
        (display_message, "str_error_string", 0),
    (try_end),
(try_end),
(store_random_in_range, ":local12", 0, 100),
(try_begin),
    (neg|ge, ":local12", 5),
    (set_trigger_result, 1),
(try_end),
],

(0 ,[
(map_free),
(ge, "$auto_menu", 1),
(jump_to_menu, "$auto_menu"),
(assign, "$auto_menu", -1), 
],

(0 ,[
(map_free),
(ge, "$auto_enter_town", 1),
(start_encounter, "$auto_enter_town"),
],

(ti_simulate_battle ,[
(eq, "$abstract_combat_system", 1),
(assign, ":local0", 0),
(store_trigger_param_1, ":ally"),
(store_trigger_param_2, ":enemy"),
(party_collect_attachments_to_party, ":ally", "p_collective_ally"),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_count_fit_missile_troops", "p_collective_ally"),
(store_div, ":local3", reg0, 20),
(val_add, ":local3", 1),
(call_script, "script_party_count_fit_missile_troops", "p_collective_enemy"),
(store_div, ":local4", reg0, 20),
(val_add, ":local4", 1),
(try_begin),
    (gt, ":local3", 0),
    (inflict_casualties_to_party_group, ":enemy", ":local3", "p_temp_casualties"),
    (call_script, "script_map_hero_status_in_abstract_battle"),
(try_end),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_calculate_regular_strength", "p_collective_enemy"),
(assign, ":local5", reg0),
(try_begin),
    (gt, ":local5", 0),
    (inflict_casualties_to_party_group, ":ally", ":local4", "p_temp_casualties"),
    (call_script, "script_map_hero_status_in_abstract_battle"),
(try_end),
(party_collect_attachments_to_party, ":ally", "p_collective_ally"),
(call_script, "script_party_calculate_regular_strength", "p_collective_ally"),
(assign, ":local6", reg0),
(party_collect_attachments_to_party, ":ally", "p_collective_ally"),
(call_script, "script_party_calculate_regular_strength", "p_collective_ally"),
(assign, ":local6", reg0),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_calculate_regular_strength", "p_collective_enemy"),
(assign, ":local5", reg0),
(try_begin),
    (this_or_next|eq, ":local5", 0),
    (eq, ":local6", 0),
    (assign, ":local0", 1),
    (try_begin),
        (eq, ":local5", 0),
        (assign, ":winner", ":ally"),
        (assign, ":loser", ":enemy"),
        (assign, ":local9", "p_collective_enemy"),
    (else_try),
        (assign, ":winner", ":enemy"),
        (assign, ":loser", ":ally"),
        (assign, ":local9", "p_collective_ally"),
    (try_end),
    (call_script, "script_get_nonempty_party_in_group", ":winner", 0),
    (assign, ":local10", reg0),
    (ge, ":local10", 0),
    (store_faction_of_party, ":local11", ":local10"),
    (store_faction_of_party, ":local12", ":loser"),
    (party_clear, "p_temp_party"),
    (assign, "$g_move_heroes", 0),
    (call_script, "script_party_add_party_prisoners", "p_temp_party", ":local9"),
    (assign, "$map_hero_root_defender_party", ":ally"),
    (assign, "$map_hero_root_attacker_party", ":enemy"),
    (call_script, "script_party_prisoners_add_party_companions", "p_temp_party", ":local9"),
    (distribute_party_among_party_group, "p_temp_party", ":winner"),
    (call_script, "script_clear_party_group", ":loser", 0),
    (set_trigger_result, 1),
    (try_begin),
        (eq, ":loser", 0),
        (display_message, "str_error_string"),
    (try_end),
(try_end),
(neg|eq, ":local0", 1),
(call_script, "script_party_count_fit_shock_troops", "p_collective_ally"),
(store_div, ":local13", reg0, 20),
(val_add, ":local13", 1),
(call_script, "script_party_count_fit_shock_troops", "p_collective_enemy"),
(store_div, ":local14", reg0, 20),
(val_add, ":local14", 1),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_calculate_regular_strength", "p_collective_enemy"),
(assign, ":local5", reg0),
(try_begin),
    (gt, ":local5", 0),
    (inflict_casualties_to_party_group, ":ally", ":local14", "p_temp_casualties"),
    (call_script, "script_map_hero_status_in_abstract_battle"),
(try_end),
(party_collect_attachments_to_party, ":ally", "p_collective_ally"),
(call_script, "script_party_calculate_regular_strength", "p_collective_ally"),
(assign, ":local6", reg0),
(try_begin),
    (gt, ":local6", 0),
    (inflict_casualties_to_party_group, ":enemy", ":local13", "p_temp_casualties"),
    (call_script, "script_map_hero_status_in_abstract_battle"),
(try_end),
(party_collect_attachments_to_party, ":ally", "p_collective_ally"),
(call_script, "script_party_calculate_regular_strength", "p_collective_ally"),
(assign, ":local6", reg0),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_calculate_regular_strength", "p_collective_enemy"),
(assign, ":local5", reg0),
(try_begin),
    (this_or_next|eq, ":local5", 0),
    (eq, ":local6", 0),
    (assign, ":local0", 1),
    (try_begin),
        (eq, ":local5", 0),
        (assign, ":winner", ":ally"),
        (assign, ":loser", ":enemy"),
        (assign, ":local9", "p_collective_enemy"),
    (else_try),
        (assign, ":winner", ":enemy"),
        (assign, ":loser", ":ally"),
        (assign, ":local9", "p_collective_ally"),
    (try_end),
    (call_script, "script_get_nonempty_party_in_group", ":winner", 0),
    (assign, ":local10", reg0),
    (ge, ":local10", 0),
    (store_faction_of_party, ":local11", ":local10"),
    (store_faction_of_party, ":local12", ":loser"),
    (party_clear, "p_temp_party"),
    (assign, "$g_move_heroes", 0),
    (call_script, "script_party_add_party_prisoners", "p_temp_party", ":local9"),
    (assign, "$map_hero_root_defender_party", ":ally"),
    (assign, "$map_hero_root_attacker_party", ":enemy"),
    (call_script, "script_party_prisoners_add_party_companions", "p_temp_party", ":local9"),
    (distribute_party_among_party_group, "p_temp_party", ":winner"),
    (call_script, "script_clear_party_group", ":loser"),
    (set_trigger_result, 1),
    (try_begin),
        (eq, ":loser", 0),
        (display_message, "str_error_string"),
    (try_end),
(try_end),
(neg|eq, ":local0", 1),
(call_script, "script_party_count_fit_melee_troops", "p_collective_ally"),
(store_div, ":local15", reg0, 20),
(val_add, ":local15", 1),
(call_script, "script_party_count_fit_melee_troops", "p_collective_enemy"),
(store_div, ":local16", reg0, 20),
(val_add, ":local16", 1),
(try_begin),
    (gt, ":local15", 0),
    (inflict_casualties_to_party_group, ":enemy", ":local15", "p_temp_casualties"),
    (call_script, "script_map_hero_status_in_abstract_battle"),
(try_end),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_calculate_regular_strength", "p_collective_enemy"),
(assign, ":local5", reg0),
(try_begin),
    (gt, ":local5", 0),
    (inflict_casualties_to_party_group, ":ally", ":local16", "p_temp_casualties"),
    (call_script, "script_map_hero_status_in_abstract_battle"),
(try_end),
(party_collect_attachments_to_party, ":ally", "p_collective_ally"),
(call_script, "script_party_calculate_regular_strength", "p_collective_ally"),
(assign, ":local6", reg0),
(party_collect_attachments_to_party, ":enemy", "p_collective_enemy"),
(call_script, "script_party_calculate_regular_strength", "p_collective_enemy"),
(assign, ":local5", reg0),
(try_begin),
    (this_or_next|eq, ":local5", 0),
    (eq, ":local6", 0),
    (try_begin),
        (eq, ":local5", 0),
        (assign, ":winner", ":ally"),
        (assign, ":loser", ":enemy"),
        (assign, ":local9", "p_collective_enemy"),
    (else_try),
        (assign, ":winner", ":enemy"),
        (assign, ":loser", ":ally"),
        (assign, ":local9", "p_collective_ally"),
    (try_end),
    (call_script, "script_get_nonempty_party_in_group", ":winner", 0),
    (assign, ":local10", reg0),
    (ge, ":local10", 0),
    (store_faction_of_party, ":local11", ":local10"),
    (store_faction_of_party, ":local12", ":loser"),
    (party_clear, "p_temp_party"),
    (assign, "$g_move_heroes", 0),
    (call_script, "script_party_add_party_prisoners", "p_temp_party", ":local9"),
    (assign, "$map_hero_root_defender_party", ":ally"),
    (assign, "$map_hero_root_attacker_party", ":enemy"),
    (call_script, "script_party_prisoners_add_party_companions", "p_temp_party", ":local9"),
    (distribute_party_among_party_group, "p_temp_party", ":winner"),
    (call_script, "script_clear_party_group", ":loser"),
    (set_trigger_result, 1),
    (try_begin),
        (eq, ":loser", 0),
        (display_message, "str_error_string"),
    (try_end),
(try_end),
(store_random_in_range, ":local17", 0, 100),
(try_begin),
    (neg|ge, ":local17", 5),
    (set_trigger_result, 1),
(try_end), 
],

(0.9 ,[
(try_begin),
    (eq, "$black_blade_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_black_blade_of_mordor"),
    (neg|gt, "$uruk_chieftain's_axe_wielded", 1),
    (neg|gt, "$westernesse_wielded", 1),
    (neg|gt, "$uruk_scorpion_blade_wielded", 1),
    (assign, "$black_blade_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_power_strike, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 1),
    (troop_raise_proficiency_linear, "trp_player", 1, 25),
    (troop_raise_skill, "trp_player", skl_power_strike, reg2),
    (display_message, "@A_black_blade_of_mordor_is_wielded", 4282811060),
    (display_message, "@(+25_two_handed_weapon,_+1_powerstrike)"),
    (assign, "$original_power_strike", reg0),
    (eq, "$black_blade_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_black_blade_of_Mordor._This_evil_blade_was_crafted_in_the_furnaces_of_Barad-dur_and_wound_round_with_spells_of_ruin_and_death._It_is_a_vile_weapon,_crafted_by_those_who_were_more_vile_still."),
    (assign, "$black_blade_first_time", 1),
(try_end),
(try_begin),
    (eq, "$black_blade_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_black_blade_of_mordor"),
    (assign, "$black_blade_wielded", 1),
    (display_message, "@A_black_blade_of_mordor_is_sheathed", 4282811060),
    (display_message, "@(-25_two_handed_weapon,_-1_powerstrike)"),
    (troop_raise_proficiency_linear, "trp_player", 1, -25),
    (neg|ge, "$original_power_strike", 10),
    (troop_raise_skill, "trp_player", skl_power_strike, -1),
(try_end), 
],

(0.9 ,[
(try_begin),
    (eq, "$wulfs_blade_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_wulfs_blade"),
    (neg|gt, "$uruk_chieftain's_axe_wielded", 1),
    (neg|gt, "$black_blade_wielded", 1),
    (neg|gt, "$westernesse_wielded", 1),
    (assign, "$wulfs_blade_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_power_strike, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_proficiency_linear, "trp_player", 1, 10),
    (troop_raise_skill, "trp_player", skl_power_strike, reg2),
    (display_message, "@The_great_blade_of_Wulf_is_wielded.", 4282811060),
    (display_message, "@(+10_two_handed_weapon,_+2_powerstrike)"),
    (assign, "$power_strike_gained_from_wulfs_blade", reg2),
    (eq, "$wulfs_blade_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_The_great_blade_of_a_Dunlending_chieftain._Once_a_symbol_of_kingship_in_Dunland,_this_blade_fell_into_Rohirrim_hands_centuries_ago_when_its_last_wielder,_the_chieftain_Wulf,_was_slain_by_Frealaf,_the_nephew_of_Helm._Its_razor-sharp_blade_will_fell_troll_or_man_with_ease."),
    (assign, "$wulfs_blade_first_time", 1),
(try_end),
(try_begin),
    (eq, "$wulfs_blade_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_wulfs_blade"),
    (assign, "$wulfs_blade_wielded", 1),
    (display_message, "@The_dunlending_blade_is_put_away.", 4282811060),
    (display_message, "@(-10_two_handed_weapon,_-2_powerstrike)"),
    (troop_raise_proficiency_linear, "trp_player", 1, -10),
    (val_mul, "$power_strike_gained_from_wulfs_blade", -1),
    (troop_raise_skill, "trp_player", skl_power_strike, "$power_strike_gained_from_wulfs_blade"),
(try_end), 
],

(0.9 ,[
(try_begin),
    (eq, "$bryttas_blade_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_bryttas_blade"),
    (neg|gt, "$wulfs_blade_wielded", 1),
    (neg|gt, "$uruk_chieftain's_axe_wielded", 1),
    (neg|gt, "$black_blade_wielded", 1),
    (neg|gt, "$westernesse_wielded", 1),
    (assign, "$bryttas_blade_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_power_strike, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_proficiency_linear, "trp_player", 1, 15),
    (troop_raise_skill, "trp_player", skl_power_strike, reg2),
    (display_message, "@The_blade_of_Brytta_is_wielded.", 4282811060),
    (display_message, "@(+15_one_handed_weapon,_+2_powerstrike)"),
    (assign, "$power_strike_gained_from_bryttas_blade", reg2),
    (eq, "$bryttas_blade_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_The_weathered_sword_of_Brytta,_an_early_king_of_Rohan._This_weapon_was_used_by_the_king_in_his_many_campaigns_against_the_orcs_of_the_north_and_it_has_somehow_retained_its_keen_edge_down_through_the_long_centuries."),
    (assign, "$bryttas_blade_first_time", 1),
(try_end),
(try_begin),
    (eq, "$bryttas_blade_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_bryttas_blade"),
    (assign, "$bryttas_blade_wielded", 1),
    (display_message, "@The_ancient_rohirric_sword_is_put_away.", 4282811060),
    (display_message, "@(-15_one_handed_weapon,_-2_powerstrike)"),
    (troop_raise_proficiency_linear, "trp_player", 1, -15),
    (val_mul, "$power_strike_gained_from_bryttas_blade", -1),
    (troop_raise_skill, "trp_player", skl_power_strike, "$power_strike_gained_from_bryttas_blade"),
(try_end), 
],

(0.9 ,[
(try_begin),
    (eq, "$uruk_chieftain's_axe_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_uruk_chieftain_s_axe"),
    (neg|gt, "$black_blade_wielded", 1),
    (neg|gt, "$westernesse_wielded", 1),
    (assign, "$uruk_chieftain's_axe_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_power_strike, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 3),
    (troop_raise_skill, "trp_player", skl_power_strike, reg2),
    (display_message, "@A_great_axe_of_the_uruk_chiefs_is_wielded.", 4282811060),
    (display_message, "@(+3_powerstrike)", 0),
    (assign, "$power_strike_gained_from_uruk_axe", reg2),
    (eq, "$uruk_chieftain's_axe_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_The_great_axe_of_a_long_dead_Uruk_chieftain._Crafted_by_men_or_orc_long_dead_and_best_forgotten,_it_has_become_filled_with_the_rage_and_twisted_hate_of_the_Uruk._It_is_a_weapon_fit_for_a_savage."),
    (assign, "$uruk_chieftain's_axe_first_time", 1),
(try_end),
(try_begin),
    (eq, "$uruk_chieftain's_axe_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_uruk_chieftain_s_axe"),
    (assign, "$uruk_chieftain's_axe_wielded", 1),
    (display_message, "@The_great_axe_of_the_Uruk_is_put_away.", 4282811060),
    (display_message, "@(-3_powerstrike)", 0),
    (val_mul, "$power_strike_gained_from_uruk_axe", -1),
    (troop_raise_skill, "trp_player", skl_power_strike, "$power_strike_gained_from_uruk_axe"),
(try_end), 
],

(0.8 ,[
(try_begin),
    (eq, "$bow_of_folca_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_bow_of_folca"),
    (neg|gt, "$goblin_king_gloves_wielded", 1),
    (neg|gt, "$galadhrim_royal_bow_wielded", 1),
    (assign, "$bow_of_folca_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_power_draw, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_power_draw, reg2),
    (troop_raise_proficiency_linear, "trp_player", 3, 15),
    (display_message, "@The_bow_of_Folca_is_wielded.", 4282811060),
    (display_message, "@(+2_powerdraw,_+15_archery)", 0),
    (assign, "$power_draw_gained_from_bow_of_folca", reg2),
    (eq, "$bow_of_folca_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_The_great_war_bow_of_Folca,_the_thirteenth_king_of_the_Riddermark._The_most_famous_hunter_of_his_time,_he_cleared_the_land_of_orcs_before_being_mortally_wounded_by_a_monstrous_boar._Few_have_the_strength_to_draw_the_string_but_those_who_can_find_a_mighty_weapon."),
    (assign, "$bow_of_folca_first_time", 1),
(try_end),
(try_begin),
    (eq, "$bow_of_folca_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_bow_of_folca"),
    (assign, "$bow_of_folca_wielded", 1),
    (display_message, "@You_put_away_the_bow_of_Folca.", 4282811060),
    (display_message, "@(-2_powerdraw,_-15_archery)", 0),
    (troop_raise_proficiency_linear, "trp_player", 3, -15),
    (val_mul, "$power_draw_gained_from_bow_of_folca", -1),
    (troop_raise_skill, "trp_player", skl_power_draw, "$power_draw_gained_from_bow_of_folca"),
(try_end), 
],

(0.9 ,[
(try_begin),
    (eq, "$galadhrim_royal_bow_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_galadhrim_royal_bow"),
    (neg|gt, "$goblin_king_gloves_wielded", 1),
    (neg|gt, "$bow_of_folca_wielded", 1),
    (assign, "$galadhrim_royal_bow_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_power_draw, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 1),
    (troop_raise_skill, "trp_player", skl_power_draw, reg2),
    (troop_raise_proficiency_linear, "trp_player", 3, 40),
    (display_message, "@The_Galadhrim_bow_is_wielded.", 4282811060),
    (display_message, "@(+1_powerdraw,_+40_archery)", 0),
    (assign, "$power_draw_gained_from_galadhrim_royal_bow", reg2),
    (eq, "$galadhrim_royal_bow_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_This_bow_has_been_crafted_by_the_elves_of_Lothlorien_and_has_been_made_with_unusual_skill,_judged_even_by_the_high_standards_of_that_folk._It_fits_easily_to_the_hand_and_sets_its_arrows_flying_with_incredible_precision."),
    (assign, "$galadhrim_royal_bow_first_time", 1),
(try_end),
(try_begin),
    (eq, "$galadhrim_royal_bow_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_galadhrim_royal_bow"),
    (assign, "$galadhrim_royal_bow_wielded", 1),
    (display_message, "@You_put_away_the_Galadhrim_bow.", 4282811060),
    (display_message, "@(-1_powerdraw,_-40_archery)", 0),
    (troop_raise_proficiency_linear, "trp_player", 3, -40),
    (val_mul, "$power_draw_gained_from_galadhrim_royal_bow", -1),
    (troop_raise_skill, "trp_player", skl_power_draw, "$power_draw_gained_from_galadhrim_royal_bow"),
(try_end), 
],

(0.7 ,[
(try_begin),
    (eq, "$iron_bow_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_iron_bow"),
    (neg|gt, "$goblin_king_gloves_wielded", 1),
    (neg|gt, "$bow_of_folca_wielded", 1),
    (neg|gt, "$galadhrim_royal_bow_wielded", 1),
    (assign, "$iron_bow_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_power_draw, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 3),
    (troop_raise_skill, "trp_player", skl_power_draw, reg2),
    (display_message, "@The_iron_bow_is_wielded.", 4282811060),
    (display_message, "@(+3_powerdraw)", 0),
    (assign, "$power_draw_gained_from_iron_bow", reg2),
    (eq, "$iron_bow_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_An_evil_bow_crafted_from_blackened_iron._Forged_by_techniques_lost_to_living_memory,_this_bow_may_have_been_crafted_using_skills_once_applied_to_the_legendary_steel_bows_of_Numenor._Whatever_its_origins,_it_is_a_brutal_weapon,_disgorging_arrows_with_devastating_power."),
    (assign, "$iron_bow_first_time", 1),
(try_end),
(try_begin),
    (eq, "$iron_bow_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_iron_bow"),
    (assign, "$iron_bow_wielded", 1),
    (display_message, "@You_put_away_the_iron_bow.", 4282811060),
    (display_message, "@(-3_powerdraw)", 0),
    (val_mul, "$power_draw_gained_from_iron_bow", -1),
    (troop_raise_skill, "trp_player", skl_power_draw, "$power_draw_gained_from_iron_bow"),
(try_end), 
],

(0.7 ,[
(try_begin),
    (eq, "$goblin_king_gloves_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_goblin_king_gloves"),
    (neg|gt, "$bow_of_brego_wielded", 1),
    (assign, "$goblin_king_gloves_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_power_draw, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 1),
    (troop_raise_proficiency_linear, "trp_player", 3, 20),
    (troop_raise_skill, "trp_player", skl_power_draw, reg2),
    (troop_raise_attribute, "trp_player", ca_strength, 1),
    (display_message, "@You_don_the_gloves_of_a_goblin_king.", 4282811060),
    (display_message, "@(+1_powerdraw,_+1_str,_+20_archery)", 0),
    (assign, "$original_power_draw", reg0),
    (eq, "$goblin_king_gloves_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_pair_of_leather_gloves_that_once_belonged_to_a_long_dead_goblin_chieftain_who_was_reknowned_as_a_marksmen._The_twisted_leather_is_inscribed_with_fell_runes_and_any_who_use_these_gloves_will_find_their_accuracy_improved."),
    (assign, "$goblin_king_gloves_first_time", 1),
(try_end),
(try_begin),
    (eq, "$goblin_king_gloves_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_goblin_king_gloves"),
    (assign, "$goblin_king_gloves_wielded", 1),
    (display_message, "@You_have_removed_the_goblin_king's_gloves", 4282811060),
    (display_message, "@(-1_powerdraw,_-1_str,_-20_archery)", 0),
    (troop_raise_proficiency_linear, "trp_player", 3, -20),
    (troop_raise_attribute, "trp_player", ca_strength, -1),
    (neg|ge, "$original_power_draw", 10),
    (troop_raise_skill, "trp_player", skl_power_draw, -1),
(try_end), 
],

(0.7 ,[
(try_begin),
    (eq, "$earnurs_helm_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_earnurs_helm"),
    (assign, "$earnurs_helm_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_ironflesh, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_ironflesh, reg2),
    (display_message, "@You_don_the_helm_of_King_Earnur.", 4282811060),
    (display_message, "@(+2_ironflesh)", 0),
    (assign, "$original_ironflesh", reg0),
    (eq, "$earnurs_helm_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_An_ancient_helm_that_once_belonged_to_the_last_true_king_of_Gondor._Though_lost_in_single_combat_with_the_Witch-King,_his_iron_will_remains_stamped_on_this_storied_heirloom."),
    (assign, "$earnurs_helm_first_time", 1),
(try_end),
(try_begin),
    (eq, "$earnurs_helm_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_earnurs_helm"),
    (assign, "$earnurs_helm_wielded", 1),
    (display_message, "@You_have_removed_the_ancient_helm_of_Earnur", 4282811060),
    (display_message, "@(-2_ironflesh)", 0),
    (neg|ge, "$original_ironflesh", 10),
    (troop_raise_skill, "trp_player", skl_ironflesh, -2),
    (eq, "$original_ironflesh", 9),
    (troop_raise_skill, "trp_player", skl_ironflesh, 1),
(try_end),
],

(1.1 ,[
(try_begin),
    (eq, "$uruk_chieftain's_helm_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_uruk_chieftain_s_helm"),
    (neg|gt, "$khamuls_helm_wielded", 1),
    (assign, "$uruk_chieftain's_helm_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_ironflesh, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_ironflesh, reg2),
    (display_message, "@You_don_the_helm_of_an_Uruk-hai_cheiftain.", 4282811060),
    (display_message, "@(+2_ironflesh)", 0),
    (assign, "$original_ironflesh", reg0),
    (eq, "$uruk_chieftain's_helm_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_helm_forged_for_the_greatest_of_Saruman's_Uruk-Hai._Dark_magics_imbue_it's_wielder_with_a_supreme_will_to_endure_all_pain."),
    (assign, "$uruk_chieftain's_helm_first_time", 1),
(try_end),
(try_begin),
    (eq, "$uruk_chieftain's_helm_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_uruk_chieftain_s_helm"),
    (assign, "$uruk_chieftain's_helm_wielded", 1),
    (display_message, "@You_have_removed_the_Uruk-hai_chieftain's_helm.", 4282811060),
    (display_message, "@(-2_ironflesh)", 0),
    (neg|ge, "$original_ironflesh", 10),
    (troop_raise_skill, "trp_player", skl_ironflesh, -2),
    (eq, "$original_ironflesh", 9),
    (troop_raise_skill, "trp_player", skl_ironflesh, 1),
(try_end), 
],

(0.8 ,[
(try_begin),
    (eq, "$khamuls_helm_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_khamuls_helm"),
    (neg|gt, "$uruk_chieftain's_helm_wielded", 1),
    (assign, "$khamuls_helm_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_ironflesh, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 1),
    (troop_raise_skill, "trp_player", skl_ironflesh, reg2),
    (display_message, "@You_don_Khamul's_helm.", 4282811060),
    (display_message, "@(+1_ironflesh,_10%_bonus_to_morale)"),
    (assign, "$original_ironflesh", reg0),
    (eq, "$khamuls_helm_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_helm_once_owned_by_the_Easterling_warlord_Khamul_who_later_became_the_lieutenant_of_the_Nazgul._In_the_years_before_he_became_a_wraith_of_Sauron_this_helm_accompanied_him_on_many_campaigns_against_upstart_warlords._It_is_exceptionally_well_forged_and_still_radiates_some_measure_of_the_terror_of_its_former_master."),
    (assign, "$khamuls_helm_first_time", 1),
(try_end),
(try_begin),
    (eq, "$khamuls_helm_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_khamuls_helm"),
    (assign, "$khamuls_helm_wielded", 1),
    (display_message, "@You_have_removed_Khamul's_helm.", 4282811060),
    (display_message, "@(-1_ironflesh,_lost_morale_bonus)"),
    (neg|ge, "$original_ironflesh", 10),
    (troop_raise_skill, "trp_player", skl_ironflesh, -1),
(try_end), 
],

(0.8 ,[
(try_begin),
    (eq, "$galadhrim_boots_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_galadhrim_boots"),
    (assign, "$galadhrim_boots_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_athletics, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_athletics, reg2),
    (display_message, "@You_don_the_boots_of_the_Galadrium.", 4282811060),
    (display_message, "@(+2_athletics)"),
    (assign, "$original_athletics", reg0),
    (eq, "$galadhrim_boots_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_Ancient_boots_crafted_long_ago_by_the_Sylvan_elves_of_Greenwood._How_they_came_to_rest_in_the_forest_of_Lothlorien_is_unknown_to_you_but_their_comfort_and_quality_have_been_remarked_upon_by_Celeborn_himself."),
    (assign, "$galadrium_boots_first_time", 1),
(try_end),
(try_begin),
    (eq, "$galadhrim_boots_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_galadhrim_boots"),
    (assign, "$galadhrim_boots_wielded", 1),
    (display_message, "@You_have_removed_the_elven_boots", 4282811060),
    (display_message, "@(-2_athletics)"),
    (neg|ge, "$original_athletics", 10),
    (troop_raise_skill, "trp_player", skl_athletics, -2),
    (eq, "$original_athletics", 9),
    (troop_raise_skill, "trp_player", skl_athletics, 1),
(try_end), 
],

(0.8 ,[
(try_begin),
    (eq, "$fell_gauntlets_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_fell_gauntlets"),
    (assign, "$fell_gauntlets_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_weapon_master, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 1),
    (troop_raise_skill, "trp_player", skl_weapon_master, reg2),
    (troop_raise_attribute, "trp_player", ca_strength, 2),
    (troop_raise_proficiency_linear, "trp_player", 0, 10),
    (troop_raise_proficiency_linear, "trp_player", 1, 10),
    (troop_raise_proficiency_linear, "trp_player", 2, 10),
    (display_message, "@You_don_the_fell_gauntlets_of_Mordor.", 4282811060),
    (display_message, "@(+2_strength,_+1_weaponmaster,_+10_all_melee_skills)"),
    (assign, "$original_athletics", reg0),
    (eq, "$fell_gauntlets_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_Cruelly_inscribed_gauntlets_from_the_black_lands._Their_origins_are_unknown_but_surely_they_are_the_work_of_Saurons_greatest_smiths."),
    (assign, "$fell_gauntlets_first_time", 1),
(try_end),
(try_begin),
    (eq, "$fell_gauntlets_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_fell_gauntlets"),
    (assign, "$fell_gauntlets_wielded", 1),
    (display_message, "@You_have_removed_the_fell_gauntlets_of_Mordor", 4282811060),
    (display_message, "@(-2_strength,_-1_weaponmaster,_-10_all_melee_skills)"),
    (troop_raise_attribute, "trp_player", ca_strength, -2),
    (troop_raise_proficiency_linear, "trp_player", 0, -10),
    (troop_raise_proficiency_linear, "trp_player", 1, -10),
    (troop_raise_proficiency_linear, "trp_player", 2, -10),
    (neg|ge, "$original_weaponmaster", 10),
    (troop_raise_skill, "trp_player", skl_weapon_master, -1),
(try_end),
],

(0.8 ,[
(try_begin),
    (eq, "$ancient_shield_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_ancient_shield"),
    (neg|gt, "$thorongil_shield_wielded", 1),
    (neg|gt, "$ancient_noldor_shield_wielded", 1),
    (assign, "$ancient_shield_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_shield, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_shield, reg2),
    (display_message, "@You_equip_an_ancient_shield_of_Gondor.", 4282811060),
    (display_message, "@(+2_shield)"),
    (assign, "$original_shield", reg0),
    (eq, "$ancient_shield_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_An_ancient_shield_that_once_belonged_to_one_of_the_earliest_kings_of_Gondor._Even_now,_centuries_after_its_making,_its_lightness_and_excellent_construction_lend_its_wielder_an_advantage_in_battle."),
    (assign, "$ancient_shield_first_time", 1),
(try_end),
(try_begin),
    (eq, "$ancient_shield_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_ancient_shield"),
    (assign, "$ancient_shield_wielded", 1),
    (display_message, "@You_put_away_the_ancient_shield_of_Gondor.", 4282811060),
    (display_message, "@(-2_shield)"),
    (neg|ge, "$original_shield", 10),
    (troop_raise_skill, "trp_player", skl_shield, -2),
    (eq, "$original_shield", 9),
    (troop_raise_skill, "trp_player", skl_shield, 1),
(try_end), 
],

(0.8 ,[
(try_begin),
    (eq, "$thorongil_shield_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_thorongil_shield"),
    (neg|gt, "$ancient_shield_wielded", 1),
    (neg|gt, "$ancient_noldor_shield_wielded", 1),
    (assign, "$thorongil_shield_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_shield, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_shield, reg2),
    (display_message, "@You_equip_the_shield_of_Thorongil.", 4282811060),
    (display_message, "@(+2_shield)"),
    (assign, "$original_shield", reg0),
    (eq, "$thorongil_shield_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_well-crafted_shield_that_was_once_wielded_by_Thorongil.__Its_exceptional_craftsmanship_provides_an_edge_to_its_wielder_in_battle."),
    (assign, "$thorongil_shield_first_time", 1),
(try_end),
(try_begin),
    (eq, "$thorongil_shield_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_thorongil_shield"),
    (assign, "$thorongil_shield_wielded", 1),
    (display_message, "@You_put_away_the_shield_of_Thorongil.", 4282811060),
    (display_message, "@(-2_shield)"),
    (neg|ge, "$original_shield", 10),
    (troop_raise_skill, "trp_player", skl_shield, -2),
    (eq, "$original_shield", 9),
    (troop_raise_skill, "trp_player", skl_shield, 1),
(try_end), 
],

(0.8 ,[
(try_begin),
    (eq, "$ancient_noldor_shield_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_ancient_noldor_shield"),
    (neg|gt, "$ancient_shield_wielded", 1),
    (neg|gt, "$thorongil_shield_wielded", 1),
    (assign, "$ancient_noldor_shield_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_shield, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_shield, reg2),
    (display_message, "@You_equip_an_ancient_noldorin_shield.", 4282811060),
    (display_message, "@(+2_shield)"),
    (assign, "$original_shield", reg0),
    (eq, "$ancient_noldor_shield_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_An_ornate_shield_crafted_by_the_Noldorin_elves_of_the_second_age.__Its_exceptional_craftsmanship_and_lightness_provide_an_edge_to_its_wielder_in_battle."),
    (assign, "$ancient_noldor_shield_first_time", 1),
(try_end),
(try_begin),
    (eq, "$ancient_noldor_shield_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_ancient_noldor_shield"),
    (assign, "$ancient_noldor_shield_wielded", 1),
    (display_message, "@You_put_away_the_ancient_noldorin_shield.", 4282811060),
    (display_message, "@(-2_shield)"),
    (neg|ge, "$original_shield", 10),
    (troop_raise_skill, "trp_player", skl_shield, -2),
    (eq, "$original_shield", 9),
    (troop_raise_skill, "trp_player", skl_shield, 1),
(try_end), 
],

(0.8 ,[
(try_begin),
    (eq, "$angmar_shield_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_angmar_shield"),
    (neg|gt, "$uruk_chieftain's_shield_wielded", 1),
    (assign, "$angmar_shield_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_shield, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_shield, reg2),
    (display_message, "@You_equip_an_ancient_shield_of_Angmar.", 4282811060),
    (display_message, "@(+2_shield)"),
    (assign, "$original_shield", reg0),
    (eq, "$angmar_shield_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_An_ancient_shield_that_once_awarded_to_one_of_the_high_captains_of_Angmar_by_the_Witch-King_himself.__The_fell_dewomers_placed_upon_it_offer_increased_protection_in_battle."),
    (assign, "$angmar_shield_first_time", 1),
(try_end),
(try_begin),
    (eq, "$angmar_shield_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_angmar_shield"),
    (assign, "$angmar_shield_wielded", 1),
    (display_message, "@You_put_away_the_ancient_shield_of_Angmar.", 4282811060),
    (display_message, "@(-2_shield)"),
    (neg|ge, "$original_shield", 10),
    (troop_raise_skill, "trp_player", skl_shield, -2),
    (eq, "$original_shield", 9),
    (troop_raise_skill, "trp_player", skl_shield, 1),
(try_end), 
],

(0.8 ,[
(try_begin),
    (eq, "$uruk_chieftain's_shield_wielded", 1),
    (troop_has_item_equipped, "trp_player", "itm_uruk_chieftain_s_shield"),
    (neg|gt, "$angmar_shield_wielded", 1),
    (assign, "$uruk_chieftain's_shield_wielded", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_shield, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_shield, reg2),
    (display_message, "@You_equip_the_uruk_chieftain's_shield.", 4282811060),
    (display_message, "@(+2_shield)"),
    (assign, "$original_shield", reg0),
    (eq, "$uruk_chieftain's_shield_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_An_iron_shield_crafted_for_the_most_fell_of_Sarumans_uruk_captains._Saruman_himself_is_rumored_to_have_been_present_at_the_forging_of_this_shield_and_its_unusual_properties_lend_credence_to_that_tale."),
    (assign, "$uruk_chieftain's_shield_first_time", 1),
(try_end),
(try_begin),
    (eq, "$uruk_chieftain's_shield_wielded", 2),
    (troop_has_item_equipped|neg, "trp_player", "itm_uruk_chieftain_s_shield"),
    (assign, "$uruk_chieftain's_shield_wielded", 1),
    (display_message, "@You_put_away_the_uruk_chieftain's_shield.", 4282811060),
    (display_message, "@(-2_shield)"),
    (neg|ge, "$original_shield", 10),
    (troop_raise_skill, "trp_player", skl_shield, -2),
    (eq, "$original_shield", 9),
    (troop_raise_skill, "trp_player", skl_shield, 1),
(try_end), 
],

(0.9 ,[
(try_begin),
    (eq, "$beregonds_horn_owned", 1),
    (player_has_item, "itm_beregonds_horn"),
    (assign, "$beregonds_horn_owned", 2),
    (assign, reg2, 10),
    (assign, reg3, 10),
    (store_skill_level, reg0, skl_leadership, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 2),
    (troop_raise_skill, "trp_player", skl_leadership, reg2),
    (display_message, "@You_possess_the_horn_of_Beregond.", 4282811060),
    (display_message, "@(+2_leadership)"),
    (eq, "$beregonds_horn_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_horn_from_the_armory_of_Gondor_that_once_belonged_to_Beregond,_a_great_captain_and_former_Steward_of_the_city._It_is_bound_in_silver_bands_and_it's_clear_call_is_said_to_inspire_men_to_action."),
    (assign, "$beregonds_horn_first_time", 1),
(try_end),
(try_begin),
    (eq, "$beregonds_horn_owned", 2),
    (player_has_item|neg, "itm_beregonds_horn"),
    (assign, "$beregonds_horn_owned", 1),
    (troop_raise_skill, "trp_player", skl_leadership, -2),
    (display_message, "@You_have_lost_Beregond's_horn", 4282811060),
    (display_message, "@(-2_leadership)"),
(try_end), 
],

(1.2 ,[
(try_begin),
    (eq, "$whip_of_angmar_owned", 1),
    (player_has_item, "itm_whip_of_angmar"),
    (assign, "$whip_of_angmar_owned", 2),
    (assign, reg2, 10),
    (assign, reg3, 10),
    (store_skill_level, reg0, skl_leadership, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 1),
    (store_skill_level, reg1, skl_prisoner_management, "trp_player"),
    (val_sub, reg3, reg1),
    (val_min, reg3, 1),
    (troop_raise_skill, "trp_player", skl_leadership, reg2),
    (troop_raise_skill, "trp_player", skl_prisoner_management, reg3),
    (display_message, "@You_possess_the_black_whip_of_Angmar.", 4282811060),
    (display_message, "@(+1_leadership,_+1_prisoner_skill,_morale_bonus)"),
    (eq, "$whip_of_angmar_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_barbed_whip_from_the_lost_kingdom_of_Angmar._Crafted_by_long_dead_servants_of_the_Witch-King_of_Angmar,_its_black_sinews_ripple_with_fell_magics._Surely_it's_sting_will_inspire_men_to_loyalty_and_obedience."),
    (assign, "$whip_of_angmar_first_time", 1),
(try_end),
(try_begin),
    (eq, "$whip_of_angmar_owned", 2),
    (player_has_item|neg, "itm_whip_of_angmar"),
    (assign, "$whip_of_angmar_owned", 1),
    (troop_raise_skill, "trp_player", skl_leadership, -1),
    (troop_raise_skill, "trp_player", skl_prisoner_management, -1),
    (display_message, "@You_have_lost_the_barbed_whip_of_Angmar", 4282811060),
    (display_message, "@(-1_leadership,_-1_prisoner_skill)"),
(try_end), 
],

(1.2 ,[
(try_begin),
    (eq, "$dunlending_torque_owned", 1),
    (player_has_item, "itm_dunlending_torque"),
    (assign, "$dunlending_torque_owned", 2),
    (troop_raise_attribute, "trp_player", ca_strength, 2),
    (display_message, "@You_possess_an_ornate_Dunlending_torque.", 4282811060),
    (display_message, "@(+2_strength,_minor_combat_regeneration)"),
    (eq, "$dunlending_torque_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_An_ornate_neck_torque_of_the_Dunlendings._Its_origins_are_unknown_but_it_has_long_been_recognized_as_an_item_of_some_power_by_the_smiths_of_Isengard._Some_say_its_essence_is_fueled_by_the_long_dead_berserkers_whom_it_once_adorned._Whatever_the_truth_may_be,_it_does_seem_to_convey_a_sense_of_strength_and_elan_to_its_wearer."),
    (assign, "$dunlending_torque_first_time", 1),
(try_end),
(try_begin),
    (eq, "$dunlending_torque_owned", 2),
    (player_has_item|neg, "itm_dunlending_torque"),
    (assign, "$dunlending_torque_owned", 1),
    (troop_raise_attribute, "trp_player", ca_strength, -2),
    (display_message, "@You_have_lost_the_ornate_dunlending_torque", 4282811060),
    (display_message, "@(-2_strength,_no_combat_regeneration)"),
(try_end), 
],

(1.2 ,[
(try_begin),
    (eq, "$ring_of_hope_owned", 1),
    (player_has_item, "itm_ring_of_hope"),
    (assign, "$ring_of_hope_owned", 2),
    (troop_raise_attribute, "trp_player", ca_charisma, 2),
    (display_message, "@You_possess_a_lesser_ring_of_power.", 4282811060),
    (display_message, "@(+2_charisma,_morale_boost,+3_influence_bonus)"),
    (eq, "$ring_of_hope_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_lesser_ring_of_power_that_was_forged_by_the_elven_smiths_of_Eregion_in_an_earlier_age._This_particular_ring_bears_an_inscription_exalting_the_Valar_known_as_Vana,_the_Ever-young._Like_other_rings_of_power,_this_rings_potential_is_linked_to_the_power_of_its_wielder."),
    (assign, "$ring_of_hope_first_time", 1),
(try_end),
(try_begin),
    (eq, "$ring_of_hope_owned", 2),
    (player_has_item|neg, "itm_ring_of_hope"),
    (assign, "$ring_of_hope_owned", 1),
    (troop_raise_attribute, "trp_player", ca_charisma, -2),
    (display_message, "@You_have_lost_the_lesser_ring_of_power", 4282811060),
    (display_message, "@(-2_charisma,_lost_morale_and_influence_bonus)"),
(try_end), 
],

(1.0 ,[
(try_begin),
    (eq, "$saddle_of_thengel_owned", 1),
    (player_has_item, "itm_saddle_of_thengel"),
    (assign, "$saddle_of_thengel_owned", 2),
    (assign, reg2, 10),
    (assign, reg3, 10),
    (store_skill_level, reg0, skl_horse_archery, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 1),
    (store_skill_level, reg1, skl_riding, "trp_player"),
    (val_sub, reg3, reg1),
    (val_min, reg3, 1),
    (troop_raise_skill, "trp_player", skl_horse_archery, reg2),
    (troop_raise_skill, "trp_player", skl_riding, reg3),
    (display_message, "@You_possess_the_superbly_crafted_saddle_of_Thengel.", 4282811060),
    (display_message, "@(+1_horse-archery,_+1_riding)"),
    (eq, "$saddle_of_thengel_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_finely_crafted_saddle_from_the_halls_of_Rohan._It_is_said_that_Thengel_himself,_a_former_king_of_Rohan,_used_this_masterwork_saddle_in_many_battles_against_his_foes._It_will_make_even_an_excellent_horse-master_a_better_rider."),
    (assign, "$saddle_of_thengel_first_time", 1),
(try_end),
(try_begin),
    (eq, "$saddle_of_thengel_owned", 2),
    (player_has_item|neg, "itm_saddle_of_thengel"),
    (assign, "$saddle_of_thengel_owned", 1),
    (troop_raise_skill, "trp_player", skl_horse_archery, -1),
    (troop_raise_skill, "trp_player", skl_riding, -1),
    (display_message, "@You_have_lost_the_fine_saddle_of_Thengel.", 4282811060),
    (display_message, "@(-1_horse-archery,_-1_riding)"),
(try_end), 
],

(1.1 ,[
(try_begin),
    (eq, "$tome_of_curses_owned", 1),
    (player_has_item, "itm_tome_of_curses"),
    (assign, "$tome_of_curses_owned", 2),
    (assign, reg2, 10),
    (store_skill_level, reg0, skl_tactics, "trp_player"),
    (val_sub, reg2, reg0),
    (val_min, reg2, 1),
    (troop_raise_skill, "trp_player", skl_tactics, reg2),
    (troop_raise_attribute, "trp_player", ca_charisma, 2),
    (display_message, "@You_possess_an_ancient_tome_of_Saruman.", 4282811060),
    (display_message, "@(+1_tactics,_+2_charisma)"),
    (eq, "$tome_of_curses_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_A_tome_of_the_high_wizard_Saruman._In_an_elegant_hand_he_has_filled_the_pages_with_simple_charms_and_trickery._The_curses_listed_here_will_spread_confusion_among_the_weak_and_lend_a_pleasing_tone_to_your_voice."),
    (assign, "$tome_of_curses_first_time", 1),
(try_end),
(try_begin),
    (eq, "$tome_of_curses_owned", 2),
    (player_has_item|neg, "itm_tome_of_curses"),
    (assign, "$tome_of_curses_owned", 1),
    (display_message, "@You_have_lost_the_tome_of_Saruman.", 4282811060),
    (display_message, "@(-1_tactics,_-2_charisma)"),
    (troop_raise_attribute, "trp_player", ca_charisma, -2),
    (troop_raise_skill, "trp_player", skl_tactics, -1),
(try_end), 
],

(1.0 ,[
(try_begin),
    (eq, "$elven_talisman_owned", 1),
    (player_has_item, "itm_elven_talisman"),
    (assign, "$elven_talisman_owned", 2),
    (assign, reg3, 10),
    (assign, reg4, 10),
    (assign, reg5, 10),
    (store_skill_level, reg0, skl_first_aid, "trp_player"),
    (val_sub, reg3, reg0),
    (val_min, reg3, 1),
    (store_skill_level, reg1, skl_surgery, "trp_player"),
    (val_sub, reg4, reg1),
    (val_min, reg4, 1),
    (store_skill_level, reg2, skl_wound_treatment, "trp_player"),
    (val_sub, reg5, reg2),
    (val_min, reg5, 1),
    (troop_raise_skill, "trp_player", skl_first_aid, reg3),
    (troop_raise_skill, "trp_player", skl_surgery, reg4),
    (troop_raise_skill, "trp_player", skl_wound_treatment, reg5),
    (display_message, "@You_possess_an_elven_talisman.", 4282811060),
    (display_message, "@(+1_first_aid,_wound_treatment,_surgery)"),
    (assign, "$original_first_aid", reg0),
    (assign, "$original_surgery", reg1),
    (assign, "$original_wound_treatment", reg2),
    (eq, "$elven_talisman_first_time", 0),
    (tutorial_box, "@You_have_aquired_a_rare_item!_An_elven_talisman_is_reputed_to_have_healing_properties._Crafted_by_the_elves_of_Beleriand_long_ago,_its_surface_feels_warm_and_strangely_soothing_to_the_touch."),
    (assign, "$elven_talisman_first_time", 1),
(try_end),
(try_begin),
    (eq, "$elven_talisman_owned", 2),
    (player_has_item|neg, "itm_elven_talisman"),
    (assign, "$elven_talisman_owned", 1),
    (display_message, "@You_have_lost_the_elven_talisman", 4282811060),
    (display_message, "@(-1_first_aid,_wound_treatment,_surgery)"),
    (try_begin),
        (neg|ge, "$original_first_aid", 10),
        (troop_raise_skill, "trp_player", skl_first_aid, -1),
    (try_end),
    (try_begin),
        (neg|ge, "$original_surgery", 10),
        (troop_raise_skill, "trp_player", skl_surgery, -1),
    (try_end),
    (try_begin),
        (neg|ge, "$original_wound_treatment", 10),
        (troop_raise_skill, "trp_player", skl_wound_treatment, -1),
    (try_end),
(try_end), 
],
