from header_common import *
from header_operations import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from ID_animations import *
from ID_troops import *
from ID_factions import *
from module_troops import *

# This file contains a heavily modified and improved version
# of Chel's morale scripts. If you modify it, please leave a 
# note telling what you did. -CC

morale_scripts = [
	
	# script_cf_correct_party_icon
	# This script sets an icon of a party relative to it's faction
	# param0 = party_id
	("cf_correct_party_icon",
	[
		(store_script_param, ":party_id", 1),
		(gt, ":party_id", -1),
		(store_faction_of_party, ":faction", ":party_id"),
		#(party_get_num_companions, ":size", ":party_id"),
		(assign, ":icon", icon_orc),
		#(assign, ":icon_med", icon_orc),
		#(assign, ":icon_big", icon_orc),
		(try_begin),
			(eq, ":faction", "fac_gondor"),
			(assign, ":icon", icon_footman_gondor),
		(else_try),
			(eq, ":faction", "fac_dwarf"),
			(assign, ":icon", icon_dwarf),
		(else_try),
			(eq, ":faction", "fac_rohan"),
			(assign, ":icon", icon_knight_rohan),
		(else_try),
			(eq, ":faction", "fac_lorien"),
			(assign, ":icon", icon_lorien_elf_a),
		(else_try),
			(eq, ":faction", "fac_imladris"),
			(assign, ":icon", icon_rivendell_elf),
		(else_try),
			(eq, ":faction", "fac_woodelf"),
			(assign, ":icon", icon_mirkwood_elf),
		(else_try),
			(eq, ":faction", "fac_dale"),
			(assign, ":icon", icon_generic_knight),
		(else_try),
			(eq, ":faction", "fac_harad"),
			(assign, ":icon", icon_harad_horseman),
		(else_try),
			(eq, ":faction", "fac_rhun"),
			(assign, ":icon", icon_easterling_horseman),
		(else_try),
			(eq, ":faction", "fac_khand"),
			(assign, ":icon", icon_cataphract),
		(else_try),
			(eq, ":faction", "fac_umbar"),
			(assign, ":icon", icon_umbar_corsair),
		(else_try),
			(eq|this_or_next, ":faction", "fac_isengard"),
			(eq|this_or_next, ":faction", "fac_mordor"),
			(eq|this_or_next, ":faction", "fac_guldur"),
			(eq|this_or_next, ":faction", "fac_moria"),
			(eq, ":faction", "fac_gundabad"),
			(assign, ":icon", icon_orc),
		(else_try),
			(eq, ":faction", "fac_dunland"),
			(assign, ":icon", icon_dunlander),
		(else_try),
			(eq, ":faction", "fac_beorn"),
			(assign, ":icon", icon_axeman),
		(try_end),
		(party_set_icon, ":party_id", ":icon"),
	]),

	# script_cf_get_tier_morale
	# This script stores the agents tier morale based on race in reg0.
	# param0 = agent
	("cf_agent_get_tier_morale",
	[
		(store_script_param, ":agent_no", 1),
		(assign, reg0, 0),
		(agent_get_troop_id,":troop", ":agent_no"),
		(store_character_level, ":level", ":troop"),	
		(try_begin),
			(is_between, ":level", 0, 7),
			(assign, reg0, 3),
		(else_try),
			(is_between, ":level", 7, 15),
			(assign, reg0, 6),
		(else_try),
			(is_between, ":level", 15, 23),
			(assign, reg0, 12),
		(else_try),
			(is_between, ":level", 23, 32),
			(assign, reg0, 18),
		(else_try),
			(assign, reg0, 25),
		(try_end),
	]),

	# script_cf_agent_get_leader
	# This script finds an agent's leader (heroes only), and stores his agent id in reg0.
	# param0 = agent
	("cf_agent_get_leader", 
	[
		(store_script_param, ":agent_no", 1),
		(assign, reg0, -1),
		(ge, ":agent_no", 0),
		(agent_get_party_id, ":party_no", ":agent_no"),
		(ge, ":party_no", 0),
		(party_stack_get_troop_id, ":troop", ":party_no", 0),
		(assign, ":continue", 1),
		(try_for_agents, ":cur_agent"),
			(eq, ":continue", 1),
			(agent_is_human, ":cur_agent"),
			(agent_get_troop_id, ":troop_no", ":cur_agent"),
			(troop_is_hero, ":troop"),
			(eq, ":troop", ":troop_no"),
			(assign, reg0, ":cur_agent"),
			(assign, ":continue", 0),
		(try_end),
	]),

	# script_cf_agent_get_leader_troop
	# This script finds an agent's leader, and stores his troop id in reg0.
	# param0 = agent
	("cf_agent_get_leader_troop", 
	[
		(store_script_param, ":agent_no", 1),
		(assign, reg0, -1),
		(ge, ":agent_no", 0),
		(agent_get_party_id, ":party_no", ":agent_no"),
		(gt, ":party_no", -1),
		(party_stack_get_troop_id, ":troop", ":party_no", 0),
		(try_begin),
			(troop_is_hero, ":troop"),
			(assign, reg0, ":troop"),
		(try_end),
	]),

	# script_cf_agent_get_faction
	# This script finds an agent's faction, and stores it in reg0.
	# param0 = agent
	("cf_agent_get_faction", 
	[
		(store_script_param, ":agent_no", 1),
		(assign, reg0, -1),
		(ge, ":agent_no", 0),
		(agent_get_troop_id, ":troop_no", ":agent_no"),
		(store_troop_faction, ":faction", ":troop_no"),
		(assign, reg0, ":faction"),
	]),

	# script_cf_agent_get_morale
	# This script calculates an agents morale, and stores it in reg1.
	# param0 = agent
	("cf_agent_get_morale", 
	[
		(store_script_param, ":agent_no", 1),
		(ge, ":agent_no", 0),
		(agent_get_class, ":class", ":agent_no"),
		(store_agent_hit_points,":hitpoints",":agent_no",0),
		(agent_get_troop_id,":troop_type", ":agent_no"),
		(troop_get_type, ":race", ":troop_type"),
		(store_character_level, ":troop_level", ":troop_type"),	
		(assign, ":leader", 0),
		(try_begin),
			(call_script, "script_cf_agent_get_leader_troop", ":agent_no"),
			(gt, reg0, -1),
			(store_skill_level,":leader","skl_leadership",reg0),
		(try_end),
		(val_div,":troop_level",10),
         	(val_div,":hitpoints",6), # CC: was 3, changed for balance.
         	(assign,reg1,100),
         	(val_sub,reg1,":hitpoints"),
         	(val_sub,reg1,":leader"),
         	(val_sub,reg1,":troop_level"),

		(try_begin), # Ents, spies and berserkers don't flee.
			(eq|this_or_next, ":troop_type", "trp_ent"),
			(eq|this_or_next, ":troop_type", "trp_spy"),
			(eq|this_or_next, ":troop_type", "trp_spy_evil"),
			(eq|this_or_next, ":troop_type", "trp_spy_partner"),
			(eq|this_or_next, ":troop_type", "trp_spy_partner_evil"),
			(eq|this_or_next, ":troop_type", "trp_beorning_carrock_berserker"),
			(eq|this_or_next, ":troop_type", "trp_variag_gladiator"),
			(eq, ":troop_type", "trp_fighting_uruk_hai_berserker"),
			(assign, reg1, -100),
		(else_try), # Wargs more likely to flee
			(is_between, ":troop_type", warg_ghost_begin, warg_ghost_end),
			(agent_get_horse, ":horse_no", ":agent_no"),
			(assign, reg1, 0),
			(try_begin),
				(ge, ":horse_no", 0),
				(assign, reg1, 100),
				(store_agent_hit_points,":hitpoints",":horse_no",0),
				(val_sub, reg1, ":hitpoints"),
			(try_end),
		(else_try), #Troll and quest parties never flee
			(agent_get_party_id, ":party_no", ":agent_no"),
			(party_get_template_id, ":template", ":party_no"),
			(eq|this_or_next, ":template", "pt_wild_troll"),
			(eq, ":template", "pt_raging_trolls"),
			(assign, reg1, -100),
		(else_try),

		# leader bonuses -CC
		(try_begin),
			(call_script, "script_cf_agent_get_leader", ":agent_no"),
			(gt, reg0, -1),
			(try_begin),
				(eq|this_or_next, ":race", tf_evil_man),
				(agent_is_alive, reg0),
				(val_sub, reg1, tld_morale_leader_important),
			(else_try),
				(eq|this_or_next, ":race", tf_gondor),
				(eq, ":race", tf_dunland),
				(agent_is_alive, reg0),
				(val_sub, reg1, tld_morale_leader_bonus),
			(else_try),
				(eq, ":race", tf_dwarf),
				(agent_is_alive|neg, reg0),
				(val_sub, reg1, tld_morale_leader_avenge),
			(else_try),
				(eq, ":race", tf_urukhai),
				(agent_is_alive|neg, reg0),
				(val_sub, reg1, tld_morale_leader_urukhai),
			(else_try),
				(agent_is_alive, reg0),
				(val_sub, reg1, tld_morale_leader_average),
			(try_end),
		(try_end),
	
		# What are the variables for enemy formations? -CC
		(assign, ":formation", formation_none),
		(try_begin),
			(agent_is_ally, ":agent_no"),
			(try_begin),
				(eq, ":class", grc_infantry),
				(assign, ":formation", "$infantry_formation_type"),
			(else_try),
				(eq, ":class", grc_archers),
				(assign, ":formation", "$archer_formation_type"),
			(else_try),
				(eq, ":class", grc_cavalry),
				(assign, ":formation", "$cavalry_formation_type"),
				(val_sub, reg1, 5), # slight bonus for cavalry units, a horse makes you a bit more bold. -CC
			(try_end),
		(try_end),

		# Formation bonuses. -CC
		(try_begin),
			(eq|this_or_next, ":race", tf_gondor),
			(eq|this_or_next, ":race", tf_male),
			(eq, ":race", tf_dunland),
			(gt, ":formation", formation_none),
			(val_sub, reg1, tld_morale_formation_bonus),
		(try_end),

		# Race bonuses / penalties. -CC
		(try_begin),
			(eq, ":race", tf_orc),
			(val_sub, reg1, tld_morale_poor),
		(else_try),
			(eq|this_or_next, ":race", tf_rohan),
			(eq, ":race", tf_dunland),
			(val_sub, reg1, tld_morale_average),
		(else_try),
			(eq|this_or_next, ":race", tf_male),
			(eq|this_or_next, ":race", tf_female),
			(eq|this_or_next, ":race", tf_gondor),
			(eq|this_or_next, ":race", tf_lorien),
			(eq|this_or_next, ":race", tf_woodelf),
			(eq, ":race", tf_uruk),
			(val_sub, reg1, tld_morale_good),
		(else_try),
			(eq|this_or_next, ":race", tf_imladris),
			(eq|this_or_next, ":race", tf_urukhai),
			(eq|this_or_next, ":race", tf_harad),
			(eq|this_or_next, ":race", tf_dwarf),
			(eq, ":race", tf_evil_man),
			(val_sub, reg1, tld_morale_very_good),
		(else_try),
			(val_sub, reg1, tld_morale_average),
		(try_end),

		# Nazgul modifier -CC
		(try_begin),
			(gt, "$nazgul_in_battle", 0),
			(agent_get_team, ":team_a", ":agent_no"),
			(try_begin),
				(teams_are_enemies, ":team_a", "$nazgul_team"),
				(store_mul, ":nazgul_modifier", "$nazgul_in_battle", 20),
				(val_add, reg1, ":nazgul_modifier"),
			(else_try),
				(store_mul, ":nazgul_modifier", "$nazgul_in_battle", 20),
				(val_sub, reg1, ":nazgul_modifier"),
			(try_end),
		(try_end),

		# faction bonuses. (mostly for easterlings: khand and haradrim). -CC
		(try_begin),
			(call_script, "script_cf_agent_get_faction", ":agent_no"),
			(gt, reg0, -1),
			(try_begin),
				(eq|this_or_next, reg0, fac_harad),
				(eq, reg0, fac_khand),
				(val_sub, reg1, 20),
			(else_try),
				(eq|this_or_next, reg0, fac_lorien), # Elves get a morale boost
				(eq|this_or_next, reg0, fac_imladris),
				(eq, reg0, fac_woodelf),
				(val_sub, reg1, 35), 
			(try_end),
		(try_end),
		
		# Rallied agents are 20% less likely to flee.
		(try_begin),
			(agent_slot_eq, ":agent_no", slot_agent_rallied, 1),
			(val_sub, reg1, 20),
		(try_end),

		# Tier morale
		(call_script, "script_cf_agent_get_tier_morale", ":agent_no"),
		(val_sub, reg1, reg0),		
		(try_end),
	]),

	# script_cf_spawn_routed_parties
	# This script spawns the routed parties nearby the player OR if there already is a routed party nearby,
	# it adds the routed troops to them.
	("cf_spawn_routed_parties", 
	[
		# Clear the parties if the morale option has been turned off.
		(try_begin),
			(eq, "$tld_option_morale", 0),
			(party_clear, "p_routed_troops"),
			(party_clear, "p_routed_allies"),
			(party_clear, "p_routed_enemies"),
			(assign, "$g_spawn_allies_routed", 0),
			(assign, "$g_spawn_enemies_routed", 0),
		(try_end),

		#(try_begin),
		#	(neq, 0, cheat_switch),
		#	(party_get_num_companions, reg10, "p_routed_troops"),
		#	(party_get_num_companions, reg11, "p_routed_allies"),
		#	(party_get_num_companions, reg12, "p_routed_enemies"),
		#	(display_message, "@DEBUG: Routed Troops: {reg10}, Routed Allies: {reg11}, Routed Enemies: {reg12}"),
		#	(assign, reg10, "$g_spawn_allies_routed"),
		#	(assign, reg11, "$g_spawn_enemies_routed"),
		#	(display_message, "@DEBUG: Spawn Allies: {reg10}, Spawn Enemies: {reg11}"),
		#(try_end),

		# Clear the parties if the total count is greater/equal to than the maximum.
		(try_begin),
			(assign, ":total_parties", 0),
      			(try_for_parties, ":unused"),
        			(val_add, ":total_parties", 1),
      			(try_end),
      			(ge, ":total_parties", "$tld_option_max_parties"),
			(assign, "$g_spawn_allies_routed", 0),
			(assign, "$g_spawn_enemies_routed", 0),
			(party_clear, "p_routed_troops"),
			(party_clear, "p_routed_allies"),
			(party_clear, "p_routed_enemies"),
		(try_end),

		(eq, "$tld_option_morale", 1),

		# Don't spawn parties w/ < 1/3 players party size. -CC

		(party_get_num_companions, reg3, "p_main_party"),
		(val_div, reg3, 3),

		# Clear empty parties
		(try_begin),
			(party_get_num_companions, ":size_us", "p_routed_troops"),
			(party_get_num_companions, ":size_allies", "p_routed_allies"),
			(store_add, ":total_size", ":size_us", ":size_allies"),
			(le, ":total_size", 0),
			(party_clear, "p_routed_troops"),
			(party_clear, "p_routed_allies"),
			(assign, "$g_spawn_enemies_routed", 0),
		(try_end),
		(try_begin),
			(party_get_num_companions, ":size_enemy", "p_routed_enemies"),
			(lt|this_or_next, ":size_enemy", reg3),
			(le, ":size_enemy", 0),
			(party_clear, "p_routed_enemies"),
			(assign, "$g_spawn_enemies_routed", 0),
		(try_end),
		(try_begin),
			(eq, "$g_spawn_allies_routed", 1),
			(try_begin),
				(assign, ":target_party", 0),
				(assign, ":found_party", 0),
      				(try_for_parties, ":cur_party"),
					(neq, ":found_party", 1),
					(party_get_template_id, ":template", ":cur_party"),
					(eq, ":template", "pt_routed_allies"),
					(store_distance_to_party_from_party, ":dist", "p_main_party", ":cur_party"),
					(lt, ":dist", 8),
					(assign, ":target_party", ":cur_party"),
					(assign, ":found_party", 1),
      				(try_end),
				(eq, ":found_party", 1),
				(call_script, "script_party_add_party", ":target_party", "p_routed_troops"),
				(call_script, "script_party_add_party", ":target_party", "p_routed_allies"),
				(party_clear, "p_routed_troops"),
				(party_clear, "p_routed_allies"),
				(assign, "$g_spawn_allies_routed", 0),
			(else_try),
				(assign, ":total_parties", 0),
      				(try_for_parties, ":unused"),
        				(val_add, ":total_parties", 1),
      				(try_end),
      				(le, ":total_parties", "$tld_option_max_parties"),
				(set_spawn_radius, 3),
            			(spawn_around_party, "p_main_party", "pt_routed_allies"),
            			(assign, ":routed_party", reg0),
				(call_script, "script_party_add_party", ":routed_party", "p_routed_troops"),
				(call_script, "script_party_add_party", ":routed_party", "p_routed_allies"),
				(party_stack_get_troop_id, ":troop", ":routed_party", 0),
				(store_troop_faction, ":faction", ":troop"),
				(party_set_faction, ":routed_party", ":faction"),
				(try_begin),
					(call_script, "script_cf_correct_party_icon", ":routed_party"),
				(try_end),
				(assign, ":max_dist", 99999),
				(assign, ":target_center", -1),	
				(try_for_range, ":cur_center", centers_begin, centers_end),
					(is_between, ":faction", kingdoms_begin, kingdoms_end),
					(party_is_active, ":cur_center"),
		     			(party_slot_eq, ":cur_center", slot_center_destroyed, 0),
		     			(party_slot_eq, ":cur_center", slot_center_is_besieged_by, -1),
					(store_distance_to_party_from_party, ":dist", ":routed_party", ":cur_center"),
					(lt, ":dist", ":max_dist"),
					(store_faction_of_party, ":party_faction", ":cur_center"),
					(faction_get_slot, ":faction_side", ":faction", slot_faction_side),
					(faction_slot_eq,":party_faction",slot_faction_side,":faction_side"),
					(assign, ":target_center", ":cur_center"),
					(assign, ":max_dist", ":dist"),
				(try_end),
				(try_begin),
					(gt, ":target_center", -1),
					(party_set_ai_behavior, ":routed_party", ai_bhvr_travel_to_party),
					(party_set_ai_object, ":routed_party", ":target_center"),
					(party_set_slot, ":routed_party", slot_party_ai_state, spai_undefined),
					(party_set_slot, ":routed_party", slot_party_ai_object, ":target_center"),					
				(try_end),	
				(party_clear, "p_routed_troops"),
				(party_clear, "p_routed_allies"),
				(assign, "$g_spawn_allies_routed", 0),
			(try_end),
		(try_end),
	
		(try_begin),
			(eq, "$g_spawn_enemies_routed", 1),
			(try_begin),
				(assign, ":target_party", 0),
				(assign, ":found_party", 0),
      				(try_for_parties, ":cur_party"),
					(neq, ":found_party", 1),
					(party_get_template_id, ":template", ":cur_party"),
					(eq, ":template", "pt_routed_enemies"),
					(store_distance_to_party_from_party, ":dist", "p_main_party", ":cur_party"),
					(lt, ":dist", 8),
					(assign, ":target_party", ":cur_party"),
					(assign, ":found_party", 1),
      				(try_end),
				(eq, ":found_party", 1),
				(call_script, "script_party_add_party", ":target_party", "p_routed_enemies"),
				(party_clear, "p_routed_enemies"),
				(assign, "$g_spawn_enemies_routed", 0),
			(else_try),
				(assign, ":total_parties", 0),
      				(try_for_parties, ":unused"),
        				(val_add, ":total_parties", 1),
      				(try_end),
      				(le, ":total_parties", "$tld_option_max_parties"),
				(eq, "$g_spawn_enemies_routed", 1),
				(set_spawn_radius, 3),
            			(spawn_around_party, "p_main_party", "pt_routed_enemies"),
            			(assign, ":routed_party", reg0),
				(call_script, "script_party_add_party", ":routed_party", "p_routed_enemies"),
				(party_stack_get_troop_id, ":troop", ":routed_party", 0),
				(store_troop_faction, ":faction", ":troop"),
				(store_relation, ":relation", ":faction", "$players_kingdom"),
				(try_begin),
					(lt, ":relation", 0),
					(party_set_faction, ":routed_party", ":faction"),
				(else_try),
					(party_set_faction, ":routed_party", "$g_encountered_party_faction"),	
				(try_end),
				(try_begin),
					(call_script, "script_cf_correct_party_icon", ":routed_party"),
				(try_end),
				(assign, ":max_dist", 99999),
				(assign, ":target_center", -1),	
				(try_for_range, ":cur_center", centers_begin, centers_end),
					(is_between, ":faction", kingdoms_begin, kingdoms_end),
					(party_is_active, ":cur_center"),
		     			(party_slot_eq, ":cur_center", slot_center_destroyed, 0),
		     			(party_slot_eq, ":cur_center", slot_center_is_besieged_by, -1),
					(store_distance_to_party_from_party, ":dist", ":routed_party", ":cur_center"),
					(lt, ":dist", ":max_dist"),
					(store_faction_of_party, ":party_faction", ":cur_center"),
					(faction_get_slot, ":faction_side", ":faction", slot_faction_side),
					(faction_slot_eq,":party_faction",slot_faction_side,":faction_side"),
					(assign, ":target_center", ":cur_center"),
					(assign, ":max_dist", ":dist"),
				(try_end),
				(try_begin),
					(gt, ":target_center", -1),
					(party_set_ai_behavior, ":routed_party", ai_bhvr_travel_to_party),
					(party_set_ai_object, ":routed_party", ":target_center"),
					(party_set_slot, ":routed_party", slot_party_ai_state, spai_undefined),
					(party_set_slot, ":routed_party", slot_party_ai_object, ":target_center"),					
				(try_end),				
				(party_clear, "p_routed_enemies"),
				(assign, "$g_spawn_enemies_routed", 0),
			(try_end),
		(try_end),
	]),

	# script_count_enemy_agents_around_agent
	# This script checks an agent for being surrounded by enemy agents, reg0 stores the number of agents
	# param1: agent to check; param2: max_distance
	("count_enemy_agents_around_agent", 
	[
		(store_script_param, ":agent_no", 1),
		(store_script_param, ":distance", 2),
		(assign, reg0, 0),
		(try_begin),
			(ge, ":agent_no", 0),
			(agent_get_position, pos1, ":agent_no"),
			(agent_get_team, ":team_a", ":agent_no"),
			(try_for_agents, ":cur_agent"),
				(agent_is_human, ":cur_agent"),
				(agent_is_alive, ":cur_agent"),
				(agent_get_position, pos2, ":cur_agent"),
				(get_distance_between_positions, ":dist", pos1, pos2),
				(lt, ":dist", ":distance"),
				(agent_get_team, ":team_b", ":cur_agent"),
				(teams_are_enemies, ":team_a", ":team_b"),
				(val_add, reg0, 1),
			(try_end),
		(try_end),
	]),

	# script_count_agents
	# This script counts an agent's enemies, and his allies
	# param1: agent to check; param2: max_distance
	# Output: reg0 = allies, reg1 = enemies
	("count_team_agents", 
	[
		(store_script_param, ":agent_no", 1),
		(assign, reg0, 0),
		(assign, reg1, 0),
		(try_begin),
			(ge, ":agent_no", 0),
			(agent_get_team, ":team_a", ":agent_no"),
			(try_for_agents, ":cur_agent"),
				(agent_get_team, ":team_b", ":cur_agent"),
				(try_begin),
					(teams_are_enemies, ":team_a", ":team_b"),
					(val_add, reg1, 1),
				(else_try),
					(val_add, reg0, 1),
				(try_end),
			(try_end),
		(try_end),
	]),
	# script_remove_agent_from_field
	# This script removes an agent from a battle and adds it to a routed party.
	# param1: agent to remove
	("remove_agent_from_field", 
	[
		(store_script_param, ":agent_no", 1),
		(agent_get_troop_id, ":troop_no", ":agent_no"),

		# Does agent have a horse? -CC
		(agent_get_horse, ":horse_no", ":agent_no"),

		# If so, remove it. -CC
		(try_begin),
			(ge, ":horse_no", 0),
			(call_script, "script_remove_agent", ":horse_no"),	
		(try_end),

		(try_begin),
			# Tell the player when a hero has left the battle. -CC
			(troop_is_hero, ":troop_no"),
      			(str_store_troop_name, s1, ":troop_no"),
			(assign, ":news_color", color_good_news),
			(try_begin),
        			(agent_is_ally, ":agent_no"),
				(assign, ":news_color", color_bad_news),
			(try_end),
			(display_message, "@{s1} has fled the battle!", ":news_color"),
			(agent_set_slot, ":agent_no", slot_agent_routed, 2),
			(call_script, "script_remove_agent", ":agent_no"),
		(else_try),
			# If the troop is not a hero and not a riderless warg, add it to a temp party. -CC
			(is_between|neg, ":troop_no", warg_ghost_begin, warg_ghost_end),
			(try_begin),
				(agent_is_ally, ":agent_no"),				
				(agent_get_party_id, ":party_no", ":agent_no"),
				(agent_get_kill_count, ":agent_killed", ":agent_no"),
				(agent_get_kill_count, ":agent_wounded", ":agent_no", 1),
				(agent_set_slot, ":agent_no", slot_agent_routed, 2),
				(call_script, "script_remove_agent", ":agent_no"),
				(agent_get_kill_count, ":agent_killed_2", ":agent_no"),
				(agent_get_kill_count, ":agent_wounded_2", ":agent_no", 1),
				(try_begin),
					# agent was killed
					(gt, ":agent_killed_2", ":agent_killed"),
			        	(try_begin),
						(eq, ":party_no", "p_main_party"),
						(party_add_members, "p_routed_troops", ":troop_no", 1),
					(else_try),
						(party_add_members, "p_routed_allies", ":troop_no", 1),
					(try_end),
					(assign, "$g_spawn_allies_routed", 1),
				(else_try),
					# agent was wounded
					(gt, ":agent_wounded_2", ":agent_wounded"),
					(party_remove_members,":party_no",":troop_no", 1),
			        	(try_begin),
						(eq, ":party_no", "p_main_party"),
						(party_add_members, "p_routed_troops", ":troop_no", 1),
					(else_try),
						(party_add_members, "p_routed_allies", ":troop_no", 1),
					(try_end),
					(assign, "$g_spawn_allies_routed", 1),
				(try_end),
			(else_try),	
			        (party_add_members, "p_routed_enemies", ":troop_no", 1),
				(try_begin),
					(agent_is_wounded, ":agent_no"),
					(party_wound_members, "p_routed_enemies", ":troop_no", 1),
				(try_end),
				(call_script, "script_remove_agent", ":agent_no"),
				(agent_set_slot, ":agent_no", slot_agent_routed, 2),
				(assign, "$g_spawn_enemies_routed", 1),
			(try_end),
		(try_end),
	]),

	# This script finds a position at the border nearest to the agent
	#
	("find_exit_position_at_pos4", 
	[
		(store_script_param, ":agent_no", 1),
		(try_begin),
			(le, ":agent_no", -1),
			(get_scene_boundaries, pos3, pos4),
			(position_get_x,":xmin",pos3),
			(position_get_y,":ymin",pos3),
			(position_get_x,":xmax",pos4),
			(position_get_y,":ymax",pos4),
			(init_position, pos20),
			(init_position, pos21),
			(init_position, pos22),
			(init_position, pos23),
			(store_random_in_range, ":rand_x", ":xmin", ":xmax"),
			(store_random_in_range, ":rand_y", ":ymin", ":ymax"),
			(position_set_x,pos20,":xmin"),
			(position_set_y,pos20,":rand_y"),
			(position_set_x,pos21,":xmax"),
			(position_set_y,pos21,":rand_y"),
			(position_set_x,pos22,":rand_x"),
			(position_set_y,pos22,":ymin"),
			(position_set_x,pos23,":rand_x"),
			(position_set_y,pos23,":ymax"),
			(store_random_in_range, ":rout_point", 0, 4),
			(val_add, ":rout_point", pos20),
			(copy_position, pos4, ":rout_point"),
			(position_set_z_to_ground_level, pos4),
		(else_try),
			(get_scene_boundaries, pos3, pos4),
			(agent_get_position, pos1, ":agent_no"),
			(position_set_z_to_ground_level, pos1),
			(position_set_z_to_ground_level, pos3),
			(position_set_z_to_ground_level, pos4),
			(position_get_x,":xmin",pos3),
			(position_get_y,":ymin",pos3),
			(position_get_x,":xmax",pos4),
			(position_get_y,":ymax",pos4),
			(position_get_x,":agent_x",pos1),
			(position_get_y,":agent_y",pos1),
			(init_position, pos20),
			(init_position, pos21),
			(init_position, pos22),
			(init_position, pos23),
			(position_set_x,pos20,":xmin"),
			(position_set_y,pos20,":agent_y"),
			(position_set_x,pos21,":xmax"),
			(position_set_y,pos21,":agent_y"),
			(position_set_x,pos22,":agent_x"),
			(position_set_y,pos22,":ymin"),
			(position_set_x,pos23,":agent_x"),
			(position_set_y,pos23,":ymax"),
			(position_set_z_to_ground_level, pos20),
			(position_set_z_to_ground_level, pos21),
			(position_set_z_to_ground_level, pos22),
			(position_set_z_to_ground_level, pos23),
			(assign, ":last_dist", 4000000),
			(try_for_range, ":index", 0, 4),
				(store_add, ":rout_point", ":index", pos20),
				(get_distance_between_positions, ":dist", pos1, ":rout_point"),
				(lt, ":dist", ":last_dist"),
				(assign, ":last_dist", ":dist"),
				(copy_position, pos4, ":rout_point"),
			(try_end),
		(try_end),
	]),

  #script_healthbars
    ("healthbars",
    [
	(assign,reg1,"$allies_coh_base"),
	(assign,reg2,"$enemies_coh"),
	(assign,reg3,"$new_kills"),
	(display_message,"@Your troops are at {reg1}% cohesion (+{reg3}% bonus), the enemy at {reg2}%!",0x6495ed),
     ]),

  #script_morale_check
    ("morale_check",
    [
	(try_begin),
		(lt,"$allies_coh",75),
              	(store_random_in_range,":routed",1,101),
              	(assign,":chance_ply",80),
              	(val_sub,":chance_ply","$allies_coh"),
                (try_begin),            
                  	(le,":routed",":chance_ply"),                   
                  	(call_script, "script_flee_allies"),
                  	(display_message,"@Morale of your troops wavers!",color_bad_news),      
		(try_end),
	(try_end),

	(try_begin),
              	(lt,"$enemies_coh",75),
              	(store_random_in_range,":routed",1,101),
              	(assign,":chance_ply",80),
              	(val_sub,":chance_ply","$enemies_coh"),
		(try_begin),  
                  	(le,":routed",":chance_ply"),                        
                  	(call_script, "script_flee_enemies"),
                  	(display_message,"@Morale of your enemies wavers!",color_good_news), 
		(try_end),            
	(try_end),
     ]),

  #script_rout_check
    ("rout_check",
    [
	(assign,":ally","$allies_coh"),
	(assign,":enemy","$enemies_coh"),
	(val_sub,":ally",":enemy"),

	(try_begin),
		(ge,":ally",tld_morale_rout_enemies),
		(call_script, "script_rout_enemies"),
		(store_mul, ":enemies_ratio", reg1, 100),
		(val_div, ":enemies_ratio", reg0),
		#(assign, reg0, ":enemies_ratio"),
		#(display_message, "@Enemies Ratio: {reg0}"),
		(try_begin),
			(gt, ":enemies_ratio", 80),
			(display_message,"@Your enemies flee in terror!",color_good_news),  
		(else_try),
			(gt, ":enemies_ratio", 50),
			(display_message,"@Many of your enemies are fleeing from battle.",color_good_news),  
		(else_try),
			(gt, ":enemies_ratio", 25),
			(display_message,"@Some of your enemies are fleeing from battle.",color_good_news),  
		(else_try),
			(gt, ":enemies_ratio", 10),
			(display_message,"@A few of your enemies are fleeing from battle.", color_good_news),  
		(try_end),
	(try_end),

	(try_begin),
		(le,":ally",tld_morale_rout_allies),
		(call_script, "script_rout_allies"),
		#(assign, reg2, reg0),
		#(assign, reg3, reg1),
		(val_sub, reg0, 1), # Remove player from agents
		(store_mul, ":allies_ratio", reg1, 100),
		(val_div, ":allies_ratio", reg0),
		#(assign, reg0, ":allies_ratio"),
		#(display_message,"@Allies Ratio = {reg0}, Routed = {reg3}, Total = {reg2}"),  
		(try_begin),
			(gt, ":allies_ratio", 80),
			(display_message,"@Your troops flee in terror!",color_bad_news),  
		(else_try),
			(gt, ":allies_ratio", 50),
			(display_message,"@Many of your troops are fleeing from battle.",color_bad_news),  
		(else_try),
			(gt, ":allies_ratio", 25),
			(display_message,"@Some of your troops are fleeing from battle.",color_bad_news),  
		(else_try),
			(gt, ":allies_ratio", 10),
			(display_message,"@A few of your troops are fleeing from battle.",color_bad_news),  
		(try_end),
	(try_end),
     ]),

	 
	 
##==============================================##
## 		FLEEING SCRIPTS 		##
##==============================================##

    ("flee_allies",
    [
	(call_script, "script_find_exit_position_at_pos4", -1),
		 
	(store_skill_level,":leader","skl_leadership","trp_player"),
	(try_for_agents,":agent"),
        	(agent_is_alive,":agent"),
        	(agent_is_human,":agent"),
        	(agent_is_ally,":agent"),
        	(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
		(val_div,":troop_level",10),
		(val_add,":hitpoints",":troop_level"),		 
        	(assign,":chance_ply",100),
        	(val_sub,":chance_ply",":hitpoints"),
        	(val_sub,":chance_ply",":leader"),
        	(val_div,":chance_ply",2),
        	(store_random_in_range,":routed",1,101),
		(try_begin),
                	(le,":routed",":chance_ply"),
			(agent_get_position,pos2,":agent"),
			(position_move_z,pos2,200,0),
                	(agent_clear_scripted_mode,":agent"),
			(call_script, "script_find_exit_position_at_pos4", ":agent"),
			(agent_set_scripted_destination,":agent",pos4,1),
               	(try_end),
	(end_try),	
     ]),

	("flee_enemies",
	[
	(call_script, "script_find_exit_position_at_pos4", -1),

	(try_for_agents,":agent"),
         	(agent_is_alive,":agent"),
         	(agent_is_human,":agent"),
         	(neg|agent_is_ally,":agent"),
         	(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
		(val_div,":troop_level",10),
		(val_add,":hitpoints",":troop_level"),		 
        	(assign,":chance_ply",100),
         	(val_sub,":chance_ply",":hitpoints"),
         	(val_sub,":chance_ply",4),
         	(val_div,":chance_ply",2),
         	(store_random_in_range,":routed",1,101),
	 	(try_begin),
                   	(le,":routed",":chance_ply"),
                	(agent_get_position,pos2,":agent"),
		 	(position_move_z,pos2,200,0),
                        (agent_clear_scripted_mode,":agent"),
			(call_script, "script_find_exit_position_at_pos4", ":agent"),
                        (agent_set_scripted_destination,":agent",pos4,1),
               (try_end),
	(end_try),	
	]),

##==============================================##
## 		ROUTING SCRIPTS 		##
##==============================================##

    ("rout_allies",
    [
	(call_script, "script_find_exit_position_at_pos4", -1),
	(assign, ":allies_routed", 0),
	(assign, ":allies_total", 0),
	(try_for_agents,":agent"),
         	(agent_is_alive,":agent"),
         	(agent_is_human,":agent"),
         	(agent_is_ally,":agent"),
		(get_player_agent_no, ":player_agent"),
		(neq, ":player_agent", ":agent"),
		(val_add, ":allies_total", 1),
		#(assign, reg0, ":chance_ply"),
		#(assign, reg1, ":routed"),
		#(display_message, "@{reg1} less than {reg0}"),
              	(try_begin),
			(call_script, "script_cf_agent_get_morale", ":agent"),
         		(assign, ":chance_ply", reg1),
         		(store_random_in_range,":routed",0,101),
                   	(le,":routed",":chance_ply"),
		   	(agent_slot_eq, ":agent", slot_agent_routed, 0),
		   	(agent_set_slot, ":agent", slot_agent_routed, 1),
              		(agent_get_position,pos2,":agent"),
		 	(position_move_z,pos2,200,0),
                        (agent_clear_scripted_mode,":agent"),
			(call_script, "script_find_exit_position_at_pos4", ":agent"),
                        (agent_set_scripted_destination,":agent",pos4,1),
           	(try_end),
		(try_begin),
		   	(agent_slot_eq, ":agent", slot_agent_routed, 1),
			(val_add, ":allies_routed", 1),
       			(store_random_in_range,":rand",1,101),
			(lt, ":rand", 33), # 33% chance.
			(agent_get_horse, ":horse", ":agent"),
			(try_begin),
				#(gt, ":horse", -1),
          			#(agent_set_animation, ":agent", "anim_nazgul_noooo_mounted_short"),
			#(else_try),
				(le, ":horse", -1),
          			(agent_set_animation, ":agent", "anim_nazgul_noooo_short"),	
			(try_end),
		(try_end),
	(try_end),
	(assign, reg0, ":allies_total"),
	(assign, reg1, ":allies_routed"),	
     ]),

    ("rout_enemies",
    [
	(call_script, "script_find_exit_position_at_pos4", -1),
	(assign, ":enemies_routed", 0),
	(assign, ":enemies_total", 0),
	(try_for_agents,":agent"),
         	(agent_is_alive,":agent"),
         	(agent_is_human,":agent"),
         	(neg|agent_is_ally,":agent"),
		(val_add, ":enemies_total", 1),
	 	(try_begin),
			(call_script, "script_cf_agent_get_morale", ":agent"),
         		(assign, ":chance_ply", reg1),
         		(store_random_in_range,":routed",0,101),
                   	(le,":routed",":chance_ply"),
		   	(agent_slot_eq, ":agent", slot_agent_routed, 0),
		   	(agent_set_slot, ":agent", slot_agent_routed, 1),
                	(agent_get_position,pos2,":agent"),
		 	(position_move_z,pos2,200,0),
                        (agent_clear_scripted_mode,":agent"),
			(call_script, "script_find_exit_position_at_pos4", ":agent"), 
                        (agent_set_scripted_destination,":agent",pos4,1),
               	(try_end),
		(try_begin),
		   	(agent_slot_eq, ":agent", slot_agent_routed, 1),
			(val_add, ":enemies_routed", 1),
       			(store_random_in_range,":rand",1,101),
			(lt, ":rand", 33), # 33% chance.
			(agent_get_horse, ":horse", ":agent"),
			(try_begin),
				#(gt, ":horse", -1),
          			#(agent_set_animation, ":agent", "anim_nazgul_noooo_mounted_short"),
			#(else_try),
				(le, ":horse", -1),
          			(agent_set_animation, ":agent", "anim_nazgul_noooo_short"),	
			(try_end),
		(try_end),
	(try_end),
	(assign, reg0, ":enemies_total"),
	(assign, reg1, ":enemies_routed"),
    ]),  

  

  #script_coherence
    ("coherence",
    [
	(get_scene_boundaries, pos3, pos4),	
	 
	(assign,":num_allies",0),
	(assign,":coh_allies",0),
	(assign,":num_enemies",0),
	(assign,":coh_enemies",0),
	(assign,":num_allies_alive",0),
	(assign,":num_enemies_alive",0),
	(assign,":num_allies_rallied",0),
	(assign,":num_enemies_rallied",0),

	(try_for_agents,":agent"),
		(agent_is_ally,":agent"),
		(agent_is_human,":agent"),
		(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
		(val_mul,":hitpoints",":troop_level"),
		(val_add,":num_allies", ":troop_level"),
		(val_add,":coh_allies",":hitpoints"),
		(try_begin),
			(agent_is_alive, ":agent"),
			(val_add, ":num_allies_alive", 1),
		(try_end),
		(try_begin),
			(agent_slot_eq,":agent",slot_agent_rallied,1),
			(val_add, ":num_allies_rallied", 1),
		(try_end),
	(else_try),
		(agent_is_human,":agent"),
		(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
		(val_mul,":hitpoints",":troop_level"),
		(val_add,":num_enemies", ":troop_level"),
		(val_add,":coh_enemies",":hitpoints"),
		(try_begin),
			(agent_is_alive, ":agent"),
			(val_add, ":num_enemies_alive", 1),
		(try_end),
		(try_begin),
			(agent_slot_eq,":agent",slot_agent_rallied,1),
			(val_add, ":num_enemies_rallied", 1),
		(try_end),
	(end_try),

	# Difference between in battle agents.
	(store_sub, ":advantage", ":num_allies_alive", ":num_enemies_alive"),
	
	(val_div,":coh_allies",":num_allies"),
	(assign,"$allies_coh_base",":coh_allies"),
	(val_add, "$allies_coh_base", ":advantage"),
	(val_add, "$allies_coh_base", ":num_allies_rallied"),

	# Nazgul penalty
	(try_begin),
		(gt, "$nazgul_in_battle", 0),
		(store_mul, ":nazgul_penalty", "$nazgul_in_battle", 15),
		(get_player_agent_no, ":player"),
		(agent_get_team, ":player_team", ":player"),
		(try_begin),
			(teams_are_enemies, "$nazgul_team", ":player_team"),
			(val_sub, "$allies_coh_base", ":nazgul_penalty"),
			(val_add, "$enemies_coh", ":nazgul_penalty"),
		(else_try),
			(val_sub, "$enemies_coh", ":nazgul_penalty"),
			(val_add, "$allies_coh_base", ":nazgul_penalty"),
		(try_end),
	(try_end),

	(try_begin),
		(lt, "$allies_coh_base", 0),
		(assign, "$allies_coh_base", 0),
	(try_end),
	(assign,"$allies_coh","$allies_coh_base"),
	(val_div,":coh_enemies",":num_enemies"),
	(assign,"$enemies_coh",":coh_enemies"),
	(val_add,"$allies_coh","$new_kills"),
	(val_sub, "$enemies_coh", ":advantage"),
	(val_add, "$enemies_coh", ":num_enemies_rallied"),
	(try_begin),
		(lt|this_or_next, "$enemies_coh", 0),
		(eq, ":num_enemies", 0),
		(assign, "$enemies_coh", 0),
	(try_end),
	(try_begin),
		(lt|this_or_next, "$allies_coh", 0),
		(eq, ":num_allies", 0),
		(assign, "$allies_coh", 0),
	(try_end),
     ]),  
]