from header_common import *
from header_operations import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from ID_animations import *
from ID_troops import *
from ID_factions import *
from module_troops import *

morale_scripts = [

# MORALE SCRIPTS:

	("find_exit_position_at_pos4", 
	[
		(store_script_param, ":agent_no", 1),
		(try_begin),
			(le, ":agent_no", -1),
			(get_scene_boundaries, pos3, pos4),
			(position_get_x,":xmin",pos3),
			(position_get_y,":ymin",pos3),
			(position_get_x,":xmax",pos4),
			(position_get_y,":ymax",pos4),
			(init_position, pos20),
			(init_position, pos21),
			(init_position, pos22),
			(init_position, pos23),
			(store_random_in_range, ":rand_x", ":xmin", ":xmax"),
			(store_random_in_range, ":rand_y", ":ymin", ":ymax"),
			(position_set_x,pos20,":xmin"),
			(position_set_y,pos20,":rand_y"),
			(position_set_x,pos21,":xmax"),
			(position_set_y,pos21,":rand_y"),
			(position_set_x,pos22,":rand_x"),
			(position_set_y,pos22,":ymin"),
			(position_set_x,pos23,":rand_x"),
			(position_set_y,pos23,":ymax"),
			(store_random_in_range, ":rout_point", 0, 4),
			(val_add, ":rout_point", pos20),
			(copy_position, pos4, ":rout_point"),
			(position_set_z_to_ground_level, pos4),
		(else_try),
			(get_scene_boundaries, pos3, pos4),
			(agent_get_position, pos1, ":agent_no"),
			(position_set_z_to_ground_level, pos1),
			(position_set_z_to_ground_level, pos3),
			(position_set_z_to_ground_level, pos4),
			(position_get_x,":xmin",pos3),
			(position_get_y,":ymin",pos3),
			(position_get_x,":xmax",pos4),
			(position_get_y,":ymax",pos4),
			(position_get_x,":agent_x",pos1),
			(position_get_y,":agent_y",pos1),
			(init_position, pos20),
			(init_position, pos21),
			(init_position, pos22),
			(init_position, pos23),
			(position_set_x,pos20,":xmin"),
			(position_set_y,pos20,":agent_y"),
			(position_set_x,pos21,":xmax"),
			(position_set_y,pos21,":agent_y"),
			(position_set_x,pos22,":agent_x"),
			(position_set_y,pos22,":ymin"),
			(position_set_x,pos23,":agent_x"),
			(position_set_y,pos23,":ymax"),
			(position_set_z_to_ground_level, pos20),
			(position_set_z_to_ground_level, pos21),
			(position_set_z_to_ground_level, pos22),
			(position_set_z_to_ground_level, pos23),
			(assign, ":last_dist", 4000000),
			(try_for_range, ":index", 0, 4),
				(store_add, ":rout_point", ":index", pos20),
				(get_distance_between_positions, ":dist", pos1, ":rout_point"),
				(lt, ":dist", ":last_dist"),
				(assign, ":last_dist", ":dist"),
				(copy_position, pos4, ":rout_point"),
			(try_end),
		(try_end),
	]),

  #script_healthbars
    ("healthbars",
    [
	(assign,reg1,"$allies_coh_base"),
	(assign,reg2,"$enemies_coh"),
	(assign,reg3,"$new_kills"),
	(display_message,"@Your troops are at {reg1}% cohesion (+{reg3}% bonus), the enemy at {reg2}%!",0x6495ed),
     ]),

  #script_morale_check
    ("morale_check",
    [
            (try_begin),
              (lt,"$allies_coh",70),
              (store_random_in_range,":routed",1,101),
              (assign,":chance_ply",85),
              (val_sub,":chance_ply","$allies_coh"),
                (try_begin),            
                  (le,":routed",":chance_ply"),             
                  (display_message,"@Morale of your troops wavers!",color_bad_news),            
                  (call_script, "script_flee_allies"),
                (try_end),
            (try_end),

            (try_begin),
              (lt,"$enemies_coh",70),
              (store_random_in_range,":routed",1,101),
              (assign,":chance_ply",85),
              (val_sub,":chance_ply","$enemies_coh"),
                (try_begin),  
                  (le,":routed",":chance_ply"),             
                  (display_message,"@Morale of your enemies wavers!",color_good_news),            
                  (call_script, "script_flee_enemies"),
                (try_end),            
            (try_end),
     ]),

  #script_rout_check
    ("rout_check",
    [
	(assign,":ally","$allies_coh"),
	(assign,":enemy","$enemies_coh"),
	(val_sub,":ally",":enemy"),

                (try_begin),
                   (ge,":ally",40),
                  (display_message,"@Your enemies flee in terror!",color_good_news),  
                  (call_script, "script_rout_enemies"),
               (try_end),

                (try_begin),
                   (le,":ally",-40),
                  (display_message,"@Your troops flee in terror!",color_bad_news),  
                  (call_script, "script_rout_allies"),
               (try_end),
     ]),

	 
	 
## script_flee
    ("flee_allies",
    [
	(call_script, "script_find_exit_position_at_pos4", -1),
		 
	(store_skill_level,":leader","skl_leadership","trp_player"),
	(try_for_agents,":agent"),
        (agent_is_alive,":agent"),
        (agent_is_human,":agent"),
        (agent_is_ally,":agent"),
        (store_agent_hit_points,":hitpoints",":agent",0),
	(agent_get_troop_id,":troop_type", ":agent"),
	(store_character_level, ":troop_level", ":troop_type"),
	(val_div,":troop_level",10),
	(val_add,":hitpoints",":troop_level"),		 
        (assign,":chance_ply",100),
        (val_sub,":chance_ply",":hitpoints"),
        (val_sub,":chance_ply",":leader"),
        (val_div,":chance_ply",2),
        (store_random_in_range,":routed",1,101),
		(try_begin),
                   	(le,":routed",":chance_ply"),
#                  	(display_message,"@One ally runs!"),  
                	(agent_get_position,pos2,":agent"),
		 	(position_move_z,pos2,200,0),
                        (agent_clear_scripted_mode,":agent"),
			(call_script, "script_find_exit_position_at_pos4", ":agent"),
                        (agent_set_scripted_destination,":agent",pos4,1),
               	(try_end),
	(end_try),	
     ]),

	("flee_enemies",
	[
	(call_script, "script_find_exit_position_at_pos4", -1),

	(try_for_agents,":agent"),
         	(agent_is_alive,":agent"),
         	(agent_is_human,":agent"),
         	(neg|agent_is_ally,":agent"),
         	(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
		(val_div,":troop_level",10),
		(val_add,":hitpoints",":troop_level"),		 
        	(assign,":chance_ply",100),
         	(val_sub,":chance_ply",":hitpoints"),
         	(val_sub,":chance_ply",4),
         	(val_div,":chance_ply",2),
         	(store_random_in_range,":routed",1,101),
	 	(try_begin),
                   	(le,":routed",":chance_ply"),
#                  	(display_message,"@One enemy runs!"),  
                	(agent_get_position,pos2,":agent"),
		 	(position_move_z,pos2,200,0),
                        (agent_clear_scripted_mode,":agent"),
			(call_script, "script_find_exit_position_at_pos4", ":agent"),
                        (agent_set_scripted_destination,":agent",pos4,1),
               (try_end),
	(end_try),	
	]),

## script_rout

    ("rout_allies",
    [
	(call_script, "script_find_exit_position_at_pos4", -1),

	(store_skill_level,":leader","skl_leadership","trp_player"),
	(try_for_agents,":agent"),
		(get_player_agent_no, ":player_agent"),
		(neq, ":player_agent", ":agent"),
         	(agent_is_alive,":agent"),
         	(agent_is_human,":agent"),
         	(agent_is_ally,":agent"),
         	(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
		(val_div,":troop_level",10),
         	(val_div,":hitpoints",3),
         	(assign,":chance_ply",100),
         	(val_sub,":chance_ply",":hitpoints"),
         	(val_sub,":chance_ply",":leader"),
         	(val_sub,":chance_ply",":troop_level"),
        	(store_random_in_range,":routed",1,101),
              	(try_begin),
                   	(le,":routed",":chance_ply"),
		   	(agent_slot_eq, ":agent", slot_agent_routed, 0),
		   	(agent_set_slot, ":agent", slot_agent_routed, 1),
              		(agent_get_position,pos2,":agent"),
		 	(position_move_z,pos2,200,0),
                        (agent_clear_scripted_mode,":agent"),
			(call_script, "script_find_exit_position_at_pos4", ":agent"),
                        (agent_set_scripted_destination,":agent",pos4,1),
           	(try_end),
	(try_end),	
     ]),

    ("rout_enemies",
    [
	(call_script, "script_find_exit_position_at_pos4", -1),
	(try_for_agents,":agent"),
         	(agent_is_alive,":agent"),
         	(agent_is_human,":agent"),
         	(neg|agent_is_ally,":agent"),
         	(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
		(val_div,":troop_level",10),
         	(val_div,":hitpoints",3),
         	(assign,":chance_ply",100),
         	(val_sub,":chance_ply",":hitpoints"),
         	(val_sub,":chance_ply",3), ## AI's Leadership bonus
         	(val_sub,":chance_ply",":troop_level"),
         	(store_random_in_range,":routed",1,101),
	 	(try_begin),
                   	(le,":routed",":chance_ply"),
		   	(agent_slot_eq, ":agent", slot_agent_routed, 0),
		   	(agent_set_slot, ":agent", slot_agent_routed, 1),
                	(agent_get_position,pos2,":agent"),
		 	(position_move_z,pos2,200,0),
                        (agent_clear_scripted_mode,":agent"),
			(call_script, "script_find_exit_position_at_pos4", ":agent"), 
                        (agent_set_scripted_destination,":agent",pos3,1),
               	(try_end),
	(try_end),
    ]),  

  

  #script_coherence
    ("coherence",
    [
	(get_scene_boundaries, pos3, pos4),	
	 
	(assign,":num_allies",0),
	(assign,":coh_allies",0),
	(assign,":num_enemies",0),
	(assign,":coh_enemies",0),
	(assign,":num_allies_alive",0),
	(assign,":num_enemies_alive",0),

	(try_for_agents,":agent"),
		(agent_is_ally,":agent"),
		(agent_is_human,":agent"),
		(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
#		(val_div,":troop_level",10),
		(val_mul,":hitpoints",":troop_level"),
		(val_add,":num_allies",":troop_level"),
		(val_add,":coh_allies",":hitpoints"),
		(try_begin),
			(agent_is_alive, ":agent"),
			(val_add, ":num_allies_alive", 1),
		(try_end),
	(else_try),
		(agent_is_human,":agent"),
		(store_agent_hit_points,":hitpoints",":agent",0),
		(agent_get_troop_id,":troop_type", ":agent"),
		(store_character_level, ":troop_level", ":troop_type"),
#		(val_div,":troop_level",10),
		(val_mul,":hitpoints",":troop_level"),
		(val_add,":num_enemies",":troop_level"),
		(val_add,":coh_enemies",":hitpoints"),
		(try_begin),
			(agent_is_alive, ":agent"),
			(val_add, ":num_enemies_alive", 1),
		(try_end),
	(end_try),

	# Difference between in battle agents.
	(store_sub, ":advantage", ":num_allies_alive", ":num_enemies_alive"),

	(val_div,":coh_allies",":num_allies"),
	(assign,"$allies_coh_base",":coh_allies"),
	(val_add, "$allies_coh_base", ":advantage"),
	(try_begin),
		(lt, "$allies_coh_base", 0),
		(assign, "$allies_coh_base", 0),
	(try_end),
	(assign,"$allies_coh","$allies_coh_base"),
	(val_div,":coh_enemies",":num_enemies"),
	(assign,"$enemies_coh",":coh_enemies"),
	(val_add,"$allies_coh","$new_kills"),
	(val_sub, "$enemies_coh", ":advantage"),
	(try_begin),
		(lt, "$enemies_coh", 0),
		(assign, "$enemies_coh", 0),
	(try_end),
	(try_begin),
		(lt, "$allies_coh", 0),
		(assign, "$allies_coh", 0),
	(try_end),
     ]),  
]